### ISSUE TITLE
Docker Support 

### ISSUE THREAD

**Issue by acc557** [eycorsican/leaf#10]
https://hub.docker.com/r/v2fly/v2fly-core

**Comment by eycorsican** [comment]
I don't get it, why Docker is necessary on a router?

**Comment by acc557** [comment]
Fair enough. 
I was thinking maybe a official docker build would be helpful for people who want to use it with docker.
https://hub.docker.com/layers/v2fly/v2fly-core/latest/images/sha256-5c7a5fd80aba2e6807c02f480f8fd586e391cbd8116ecb3fe0167f6fa309e8e5?context=explore
