### ISSUE TITLE
[Feature Request] Support menaul select proxy group

### ISSUE THREAD

**Issue by cielpy** [eycorsican/leaf#109]
leaf already has a wide variety of proxy groups, but there is no select proxy group, the lack of this feature causes the user can not manually adjust, but rely on the program's algorithm, I think it is necessary to add this feature.

**Comment by eycorsican** [comment]
To be honest, I don't quite understand what is a "select group", I thought it's a UI feature which the UI program shows a list of outbounds  to the user and composes a config with that user-selected outbound as the default outbound, and has nothing to do with leaf itself.

**Comment by cielpy** [comment]
Move this feature to UI program did make sense, but this have some con

1. It is it makes UI program a bit complex because UI program need to edit the config file by code, in particular config have some comment, UI program need to convert the modified config to file with comment.
2. UI program's select group maybe not sync with the config file have, this will failed when reload config.

The other hand, edit config with UI is necessary for user experience, con 1 is a problem for a demo but not for a product use case.

And con 2, select group also need to be stay sync with the other group add or remove. It's common when I use Clash.

If leaf does not have a plan to add this feature, it's ok.

**Comment by cielpy** [comment]
If want to create a "dynamic proxy chain", thought about this case

RelaySelect = select, p1, p2, p3
RelayGroup = select, p1, p2, p3, relay=RelaySelect
RelayGroup2 = p4, relay=RelaySelect

It's possible to implement base on the existed feature, it needs to edit the config file when every change occurs, for now, leaf only has an API `run_leaf`, when config changed, the UI program needs to restart leaf, the connection established will interrupt.

This is the third con to implement "select group" in the UI program.

**Comment by eycorsican** [comment]
It's a mystery to me how this feature works in other proxy tools such as Clash, do you have any idea how we can implement this in leaf?

**Comment by cielpy** [comment]
Many use cases with tools such as Clash and QuantumltX etc have multiple outbound, such as Youtube outbound, Netflix outbound, telegram outbound, etc. And personally, I always combine a select group and url-test group with a fallback group, because I would prefer manual choose which node to use, and fallback with a url-test group to keep high availability.

The point is it's better to consider "select group" as a plain group of proxy with users have the right to choose.

**Comment by eycorsican** [comment]
Alright, I think I've got the idea. Let me see how I can implement this, I think at least the following would be needed:

1. Add a `select` outbound
2. Find a way to modify the `select` outbound dynamically, perhaps through channels or apply an RwLock to the outbound
3. Expose an API to the UI  program, FFI or RESTful

**Comment by cielpy** [comment]
I see this feature has merged to master, can I test this feature ？

**Comment by eycorsican** [comment]
The feature is basically working, here's an example:
```ini
[General]
loglevel = trace
dns-server = 223.5.5.5
api-interface = 127.0.0.1
api-port = 9991
http-interface = 127.0.0.1
http-port = 1087
[Proxy]
p1 = direct
p2 = direct
[Proxy Group]
s1 = select, p1, p2
[Rule]
FINAL, s1
```

```sh
$ curl -v -X POST "http://127.0.0.1:9991/api/v1/app/outbound/select?outbound=s1&select=p2"
```

**Comment by cielpy** [comment]
I have tested it last night, there are some improvements, you said the feature is basically working, maybe you will do something like this in the future.

1. it's better to have a default selection for a select group, it could be the first outbound of the group, for now before the user selects one, all requests will fail because no outbound selected.
2. it's better to persistent the select state in the core, and restore when leaf restart, UI program can restore this state with the API but have some problem, because leaf block the running thread, so the UI program does not know when the core's API is ready to call, so it's common to delay the call, if the delay too short, this restore will unstable, if too long, some requests will fail. So I think it's better to let the leaf core persistent the statue and restore it.

**Comment by eycorsican** [comment]
> I have tested it last night, there are some improvements, you said the feature is basically working, maybe you will do something like this in the future.
> 
>     1. it's better to have a default selection for a select group, it could be the first outbound of the group, for now before the user selects one, all requests will fail because no outbound selected.
> 
>     2. it's better to persistent the select state in the core, and restore when leaf restart, UI program can restore this state with the API but have some problem, because leaf block the running thread, so the UI program does not know when the core's API is ready to call, so it's common to delay the call, if the delay too short, this restore will unstable, if too long, some requests will fail. So I think it's better to let the leaf core persistent the statue and restore it.

Good points, I'll address these improvements later.

**Comment by cielpy** [comment]
Since the leaf core has managed the select state, there is a missing and API that gets the current selection, mainly for display usage.

**Comment by cielpy** [comment]
And for url-test outbound, have the ability to get the test result is good, also for display usage.

**Comment by cielpy** [comment]
It seems that select change does not take effect

first, select 3
```
$ cat /Users/xxx/.xx/cache/selector.cache


Select
      x1.0香港3

ProxySelect%
```

```
[37m[2021-04-15 01:03:47][[37mDEBUG[0m[37m] looking up domain www.google.com on 114.114.114.114:53[0m
[37m[2021-04-15 01:03:47][[37mDEBUG[0m[37m] looking up domain www.google.com on 223.5.5.5:53[0m
[37m[2021-04-15 01:03:47][[37mDEBUG[0m[37m] looking up domain www.google.com on 114.114.114.114:53[0m
[37m[2021-04-15 01:03:47][[37mDEBUG[0m[37m] looking up domain www.google.com on 223.5.5.5:53[0m
[37m[2021-04-15 01:03:47][[37mDEBUG[0m[37m] return 1 ips for www.google.com from 223.5.5.5:53 in 7ms[0m
[90m[2021-04-15 01:03:47][[90mTRACE[0m[90m] ips for www.google.com:
[
    69.171.248.65,
][0m
[37m[2021-04-15 01:03:47][[37mDEBUG[0m[37m] return 1 ips for www.google.com from 223.5.5.5:53 in 7ms[0m
[90m[2021-04-15 01:03:47][[90mTRACE[0m[90m] ips for www.google.com:
[
    2001::45ab:f40f,
][0m
[90m[2021-04-15 01:03:47][[90mTRACE[0m[90m] re-matching with resolved ip [69.171.248.65] for [www.google.com][0m
[90m[2021-04-15 01:03:47][[90mTRACE[0m[90m] pick route failed: no matching rules[0m
[37m[2021-04-15 01:03:47][[37mDEBUG[0m[37m] picked default route [Proxy] for 127.0.0.1:56295 -> www.google.com:443[0m
[90m[2021-04-15 01:03:47][[90mTRACE[0m[90m] active proxied tcp connections +1: 1[0m
[37m[2021-04-15 01:03:47][[37mDEBUG[0m[37m] select handles tcp [www.google.com:443] to [Select][0m
[37m[2021-04-15 01:03:47][[37mDEBUG[0m[37m] select handles tcp [www.google.com:443] to [x1.0香港3][0m
[37m[2021-04-15 01:03:47][[37mDEBUG[0m[37m] looking up domain xxxx on 114.114.114.114:53[0m
[37m[2021-04-15 01:03:47][[37mDEBUG[0m[37m] looking up domain xxxx on 223.5.5.5:53[0m
[37m[2021-04-15 01:03:47][[37mDEBUG[0m[37m] looking up domain xxxx on 114.114.114.114:53[0m
[37m[2021-04-15 01:03:47][[37mDEBUG[0m[37m] looking up domain xxxx on 223.5.5.5:53[0m
[37m[2021-04-15 01:03:47][[37mDEBUG[0m[37m] return 1 ips for xxxx from 223.5.5.5:53 in 7ms[0m
[90m[2021-04-15 01:03:47][[90mTRACE[0m[90m] ips for xxxx:
[
    xxxx,
][0m
[90m[2021-04-15 01:03:47][[90mTRACE[0m[90m] dialing tcp xxxx:xxxx[0m
[90m[2021-04-15 01:03:49][[90mTRACE[0m[90m] connected tcp xxxx:xxxx[0m
[37m[2021-04-15 01:03:49][[32mINFO[0m[37m] [socks] [tcp] [Proxy] [1228ms] www.google.com:443[0m
[37m[2021-04-15 01:03:49][[37mDEBUG[0m[37m] tcp uplink 127.0.0.1:56295 -> www.google.com:443 error: Connection reset by peer (os error 54) [Proxy][0m
[90m[2021-04-15 01:03:49][[90mTRACE[0m[90m] applied 4s downlink timeout to 127.0.0.1:56295 <- www.google.com:443[0m
[37m[2021-04-15 01:03:49][[37mDEBUG[0m[37m] tcp downlink 127.0.0.1:56295 <- www.google.com:443 error: early eof [Proxy][0m
[37m[2021-04-15 01:03:49][[37mDEBUG[0m[37m] tcp downlink 127.0.0.1:56295 <- www.google.com:443 error: Socket is not connected (os error 57) [Proxy][0m
[90m[2021-04-15 01:03:49][[90mTRACE[0m[90m] active proxied tcp connections -1: 0[0m
```


then select 2

```
$ cat /Users/xxx/.xx/cache/selector.cache


ProxySelect

Select
      x1.0香港2%
```


```
[90m[2021-04-15 01:09:00][[90mTRACE[0m[90m] re-matching with resolved ip [69.171.248.65] for [www.google.com][0m
[90m[2021-04-15 01:09:00][[90mTRACE[0m[90m] pick route failed: no matching rules[0m
[37m[2021-04-15 01:09:00][[37mDEBUG[0m[37m] picked default route [Proxy] for 127.0.0.1:57463 -> www.google.com:443[0m
[90m[2021-04-15 01:09:00][[90mTRACE[0m[90m] active proxied tcp connections +1: 1[0m
[37m[2021-04-15 01:09:00][[37mDEBUG[0m[37m] select handles tcp [www.google.com:443] to [Select][0m
[37m[2021-04-15 01:09:00][[37mDEBUG[0m[37m] select handles tcp [www.google.com:443] to [x1.0香港3][0m
[90m[2021-04-15 01:09:00][[90mTRACE[0m[90m] dialing tcp :xxxx:xxxx[0m
[90m[2021-04-15 01:09:00][[90mTRACE[0m[90m] connected tcp :xxxx:xxxx[0m
[37m[2021-04-15 01:09:00][[32mINFO[0m[37m] [socks] [tcp] [Proxy] [58ms] www.google.com:443[0m
[37m[2021-04-15 01:09:01][[37mDEBUG[0m[37m] tcp uplink 127.0.0.1:57463 -> www.google.com:443 error: Connection reset by peer (os error 54) [Proxy][0m
[90m[2021-04-15 01:09:01][[90mTRACE[0m[90m] applied 4s downlink timeout to 127.0.0.1:57463 <- www.google.com:443[0m
[37m[2021-04-15 01:09:01][[37mDEBUG[0m[37m] tcp downlink 127.0.0.1:57463 <- www.google.com:443 error: early eof [Proxy][0m
[37m[2021-04-15 01:09:01][[37mDEBUG[0m[37m] tcp downlink 127.0.0.1:57463 <- www.google.com:443 error: Socket is not connected (os error 57) [Proxy][0m
[90m[2021-04-15 01:09:01][[90mTRACE[0m[90m] active proxied tcp connections -1: 0[0m
```

**Comment by eycorsican** [comment]
> It seems that select change does not take effect

https://github.com/eycorsican/leaf/commit/7324093730447800e2b8829fa015257a3c930dbb should fix this.

**Comment by cielpy** [comment]
select mode cannot select an outbound with the name that has space, return HTTP 202

**Comment by cielpy** [comment]
> select mode cannot select an outbound with the name that has space, return HTTP 202

I need more tests, curl is ok, but my code is not.

**Comment by cielpy** [comment]
> select mode cannot select an outbound with the name that has space, return HTTP 202

This issue is caused by my code, not leaf.
