### ISSUE TITLE
[Feature Request] Configuration reload on the fly

### ISSUE THREAD

**Issue by bdbai** [eycorsican/leaf#111]
Is it possible to reload configuration when Leaf is running?

In order to detect changes, Leaf may watch configuration file changes and expose a function through FFI to trigger manual reload.

Also see https://github.com/YtFlow/Maple/issues/5 .

**Comment by eycorsican** [comment]
There should be two approaches, restart and reload. We can shutdown the current tokio runtime and create a new runtime with the new configuration, or we can retain the runtime and apply new configurations to the apps via locks, the former seems simpler but has its problems, especially when we need to reopen system resources such as fds, the latter needs more coding efforts but it's the most feasible way IMO.

**Comment by bdbai** [comment]
> We can shutdown the current tokio runtime and create a new runtime with the new configuration

Simply restarting the runtime causes all connections to be closed immediately. This may introduce network interrupts system-wide.

> or we can retain the runtime and apply new configurations to the apps via locks

[arc-swap](https://crates.io/crates/arc-swap/1.2.0) seems like a better solution, which has been utilized in shadowsocks-rust.

**Comment by eycorsican** [comment]
Configuration loading is not a blocking operation, do you think we still need something like arc swap rather than simply use RwLock<Arc<T>>?

**Comment by eycorsican** [comment]
Also we may want to retain some states of the old app, e.g. the dns client cache and fake dns cache, although we can copy them into to the new object, but there's additional complexity here.

Using RwLock<T> alone and has a reload method on each app would be a cleaner option, but blocking read accesses could delay configuration reloading.

**Comment by bdbai** [comment]
IMHO `ArcSwap` is much more lightweight than `RwLock` or `Mutex` in terms of read operations.

**Comment by eycorsican** [comment]
A preliminary implementation of this feature has been added to master.
