### ISSUE TITLE
[Feature Request] Configuration Validation

### ISSUE THREAD

**Issue by bdbai** [eycorsican/leaf#112]
It would be good to expose configuration file validation through command line and FFI function. Further discussion is needed for API interface.

Also see https://github.com/YtFlow/Maple/issues/5 .

**Comment by bdbai** [comment]
Is the `conf` parser too error-tolerant to detect common mistakes in configurations? I tries many times but failed to get a configuration that made `leaf_test_config` complain...

**Comment by eycorsican** [comment]
I think we can identify a great majority of the common config mistakes by simply reporting unrecognized keywords?

**Comment by bdbai** [comment]
What about missing comma or incomplete section headers (say `[Proxy Grou`)?

**Comment by eycorsican** [comment]
Missing commas can trigger unrecognized keyword error in most cases, implementing this feature is quite easy, we can write some unit tests to see how it works.

I think we can at most detecting syntax errors, if a user is typing a wrong password for an ss outbound, there's nothing we can do here, in this sense the user takes responsibility to make sure a properly configured outbound is provided,  including the `method` param.

**Comment by bdbai** [comment]
https://github.com/eycorsican/leaf/blob/8c7e442f071d084c6a7461323fd181d66a8e279f/leaf/src/config/conf/config.rs#L767-L771

If a user forget to specify a `method` or the field is ignored because of some syntax errors, a default value of `chacha20-ietf-poly1305` will be given. In this case, reporting an error seems better than assuming anything?

This is just an example and there are a few more similar situations. Some of these errors are not detected until Leaf is starting up or actually running.

**Comment by eycorsican** [comment]
I would be ok with either. Having reasonable defaults allows compact configs, but can also cause issues in corner cases.

Please note the existing `conf` parser is not intent to be a rigorous one, the goal is just to provide an easy to read and edit config format, though I would like to improve it as much as I can. And I'm not against adding a new and better parser if you're going to pick up the job :)
