### ISSUE TITLE
Need root permissions when use tun feature

### ISSUE THREAD

**Issue by cielpy** [eycorsican/leaf#113]
System: macOS 11.1
leaf version: v0.2.14

```
[2021-04-07 18:29:57][INFO] inbound listening tcp 127.0.0.1:1086
[2021-04-07 18:29:57][INFO] inbound listening udp 127.0.0.1:1086
[2021-04-07 18:29:57][INFO] inbound listening tcp 127.0.0.1:1087
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" })', leaf/src/proxy/tun/inbound.rs:75:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Must this feature need root permission?

**Comment by eycorsican** [comment]
Sure, the tun inbound impl on macOS  uses the builtin tun/tap device  which requires the permissions.

**Comment by cielpy** [comment]
Why Surge on Mac not need the permission? 

Can I setup the tun device with the helper process? the helper has root permission.

**Comment by eycorsican** [comment]
I don't have a copy of Surge on my machine, I don't known how it works. Do you mean something like this: https://github.com/mellow-io/mellow/blob/master/src/helper/darwin/install_helper ?

**Comment by cielpy** [comment]
> I don't have a copy of Surge on my machine, I don't known how it works. Do you mean something like this: https://github.com/mellow-io/mellow/blob/master/src/helper/darwin/install_helper ?

YES! Only helper has root permission, not the whole app.

**Comment by cielpy** [comment]
```
$ ls -l /Applications/ClashX\ Pro.app/Contents/MacOS
total 71288
-rwxr-xr-x  1 xxx  admin  36499424 Mar 10 20:39 ClashX Pro
```

It seems when installing the helper, the binary's permission has changed to root.

**Comment by eycorsican** [comment]
This is the `admin`  user  group,  not the root  user, and this `ClashX Pro` executable is just the UI program I suppose.

If what you want is to run leaf's tun inbound without typing the password every time you start the program as a non-root user, all you need to do is:
```
chown root leaf
chmod  +sx leaf
```

**Comment by eycorsican** [comment]
See `man setuid` for  more details.

**Comment by cielpy** [comment]
Yes, this is the right way.
