### ISSUE TITLE
Support config default resource folder

### ISSUE THREAD

**Issue by cielpy** [eycorsican/leaf#115]
For now, resource file like geo IP db, site.dat must locate at the same folder of executable file, build macOS app with the static library, the leaf core will be bundled to the app and generate a single executable file, this folder is hard to write file to it, I can't find a normal way to do this, also, macOS app have signature include resource file, if want to update resource after install, the solution may be a little tricky, so bundle resource to the executable file's folder or update the resource is hard.

I think it's better to have a config to set the default resource file location, this config can not for users, but for developers.

**Comment by cielpy** [comment]
```
.
├── xxxxx.app
│   └── Contents
│       ├── Info.plist
│       ├── MacOS
│       │   └── xxxxx  <---------------------------------This is the executable file
│       ├── PkgInfo
│       ├── Resources <--------------------------------This is the common place where the resource file located.
│       │   ├── AppIcon.icns
│       │   ├── Assets.car
│       │   ├── Base.lproj
│       │   ├── install_helper.sh
│       │   ├── xxxxx_sysconf
│       │   └── set_route.sh
│       └── _CodeSignature
│           └── CodeResources
├── xxxxx.swiftmodule
│   ├── Project
│   │   ├── x86_64-apple-macos.swiftsourceinfo
│   │   └── x86_64.swiftsourceinfo
│   ├── x86_64-apple-macos.swiftdoc
│   ├── x86_64-apple-macos.swiftmodule
│   ├── x86_64.swiftdoc
│   └── x86_64.swiftmodule
├── NetUtils.o
├── NetUtils.swiftmodule
│   ├── Project
│   │   ├── x86_64-apple-macos.swiftsourceinfo
│   │   └── x86_64.swiftsourceinfo
│   ├── x86_64-apple-macos.swiftdoc
│   ├── x86_64-apple-macos.swiftmodule
│   ├── x86_64.swiftdoc
│   └── x86_64.swiftmodule
└── xxxxx_sysconf
```

**Comment by eycorsican** [comment]
How about having an env var  `ASSET_LOCATION=/data/folder` for this?

**Comment by cielpy** [comment]
Seem not ok, env need to set before app start, I have done a little research just now, there is no way to do this, users only have one choice, set system env, this seems not the right way.

**Comment by eycorsican** [comment]
Env var evaluation in leaf are lazy (evaluate on first  access), you can set it at runtime like: https://github.com/eycorsican/ileaf/blob/4092c509cf8d97659093f83bf7463ff5ab2d8682/PacketTunnel/PacketTunnelProvider.swift#L39 , just before you call `run_leaf`.

**Comment by cielpy** [comment]
WoW! I did not find this API. I have test it works, the env solution is fine.

**Comment by cielpy** [comment]
I have created a PR https://github.com/eycorsican/leaf/pull/119 to implement this feature.
