### ISSUE TITLE
centos 7 could not compile `leaf`

### ISSUE THREAD

**Issue by CHORDTAAX** [eycorsican/leaf#118]
error: could not compile `leaf`

Caused by:
  process didn't exit successfully: `rustc --crate-name leaf --edition=2018 leaf/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="aes"' --cfg 'feature="all-configs"' --cfg 'feature="all-endpoints"' --cfg 'feature="api"' --cfg 'feature="async-socks5"' --cfg 'feature="cfb-mode"' --cfg 'feature="config-conf"' --cfg 'feature="config-json"' --cfg 'feature="default-ring"' --cfg 'feature="digest"' --cfg 'feature="h2"' --cfg 'feature="hex"' --cfg 'feature="hkdf"' --cfg 'feature="hmac"' --cfg 'feature="http"' --cfg 'feature="hyper"' --cfg 'feature="inbound-amux"' --cfg 'feature="inbound-chain"' --cfg 'feature="inbound-http"' --cfg 'feature="inbound-quic"' --cfg 'feature="inbound-shadowsocks"' --cfg 'feature="inbound-socks"' --cfg 'feature="inbound-trojan"' --cfg 'feature="inbound-tun"' --cfg 'feature="inbound-ws"' --cfg 'feature="lru_time_cache"' --cfg 'feature="lz_fnv"' --cfg 'feature="md-5"' --cfg 'feature="outbound-amux"' --cfg 'feature="outbound-chain"' --cfg 'feature="outbound-direct"' --cfg 'feature="outbound-drop"' --cfg 'feature="outbound-failover"' --cfg 'feature="outbound-h2"' --cfg 'feature="outbound-quic"' --cfg 'feature="outbound-random"' --cfg 'feature="outbound-redirect"' --cfg 'feature="outbound-retry"' --cfg 'feature="outbound-select"' --cfg 'feature="outbound-shadowsocks"' --cfg 'feature="outbound-socks"' --cfg 'feature="outbound-tls"' --cfg 'feature="outbound-trojan"' --cfg 'feature="outbound-tryall"' --cfg 'feature="outbound-vmess"' --cfg 'feature="outbound-ws"' --cfg 'feature="quinn"' --cfg 'feature="regex"' --cfg 'feature="ring"' --cfg 'feature="ring-aead"' --cfg 'feature="rustls"' --cfg 'feature="rustls-tls"' --cfg 'feature="serde"' --cfg 'feature="serde_derive"' --cfg 'feature="serde_json"' --cfg 'feature="sha-1"' --cfg 'feature="sha2"' --cfg 'feature="sha3"' --cfg 'feature="tokio-rustls"' --cfg 'feature="tokio-tungstenite"' --cfg 'feature="tokio-util"' --cfg 'feature="tun"' --cfg 'feature="tungstenite"' --cfg 'feature="url"' --cfg 'feature="uuid"' --cfg 'feature="warp"' --cfg 'feature="webpki-roots"' -C metadata=e8246080bdcbce08 -C extra-filename=-e8246080bdcbce08 --out-dir /root/leaf/target/debug/deps -C incremental=/root/leaf/target/debug/incremental -L dependency=/root/leaf/target/debug/deps --extern aes=/root/leaf/target/debug/deps/libaes-1e57c887a1fb5c8c.rmeta --extern anyhow=/root/leaf/target/debug/deps/libanyhow-af47ab8c672d4ea6.rmeta --extern async_socks5=/root/leaf/target/debug/deps/libasync_socks5-bac77eb7e1024d81.rmeta --extern async_trait=/root/leaf/target/debug/deps/libasync_trait-f812e1bfde7c009b.so --extern byteorder=/root/leaf/target/debug/deps/libbyteorder-3ba0d986ba1f8d3d.rmeta --extern bytes=/root/leaf/target/debug/deps/libbytes-3d3cd767ba9acc00.rmeta --extern cfb_mode=/root/leaf/target/debug/deps/libcfb_mode-2411eb38198c200a.rmeta --extern chrono=/root/leaf/target/debug/deps/libchrono-6675b5c46a71cdf6.rmeta --extern cidr=/root/leaf/target/debug/deps/libcidr-48ddb83329b67d13.rmeta --extern colored=/root/leaf/target/debug/deps/libcolored-02683149c143b797.rmeta --extern digest=/root/leaf/target/debug/deps/libdigest-08ce612fb81510b2.rmeta --extern fern=/root/leaf/target/debug/deps/libfern-085a1b5a96b2d2aa.rmeta --extern futures=/root/leaf/target/debug/deps/libfutures-7423dd37ce5f009d.rmeta --extern futures_util=/root/leaf/target/debug/deps/libfutures_util-78055d925c31526d.rmeta --extern h2=/root/leaf/target/debug/deps/libh2-fa7649fd346bedc7.rmeta --extern hex=/root/leaf/target/debug/deps/libhex-fa3c317fb6d435ff.rmeta --extern hkdf=/root/leaf/target/debug/deps/libhkdf-7a7b5463105cb087.rmeta --extern hmac=/root/leaf/target/debug/deps/libhmac-aaf4037627647a42.rmeta --extern http=/root/leaf/target/debug/deps/libhttp-6f8ea42517ae40e0.rmeta --extern hyper=/root/leaf/target/debug/deps/libhyper-8567b50be38344fa.rlib --extern lazy_static=/root/leaf/target/debug/deps/liblazy_static-1fa5e8b52f04e552.rmeta --extern log=/root/leaf/target/debug/deps/liblog-dca2cf0e9e290ca2.rmeta --extern lru=/root/leaf/target/debug/deps/liblru-03262708ea95012d.rmeta --extern lru_time_cache=/root/leaf/target/debug/deps/liblru_time_cache-839e86093d0709a1.rmeta --extern lz_fnv=/root/leaf/target/debug/deps/liblz_fnv-00b8d95990f431c4.rmeta --extern maxminddb=/root/leaf/target/debug/deps/libmaxminddb-7d151c96a60a8a42.rmeta --extern md5=/root/leaf/target/debug/deps/libmd5-ea6ee1066fa69f3a.rmeta --extern memmap=/root/leaf/target/debug/deps/libmemmap-2ee105107ce04461.rmeta --extern protobuf=/root/leaf/target/debug/deps/libprotobuf-e43f80596f921d2e.rmeta --extern quinn=/root/leaf/target/debug/deps/libquinn-3138052807a4c1b8.rmeta --extern rand=/root/leaf/target/debug/deps/librand-2a8696016c7f9e49.rmeta --extern regex=/root/leaf/target/debug/deps/libregex-a3ea17b6ff423341.rmeta --extern ring=/root/leaf/target/debug/deps/libring-3b0a8eb36f9f56d4.rmeta --extern rustls=/root/leaf/target/debug/deps/librustls-6938df224cb36a60.rmeta --extern serde=/root/leaf/target/debug/deps/libserde-9abe7c4275ac0b44.rmeta --extern serde_derive=/root/leaf/target/debug/deps/libserde_derive-5cbcc1a17002af44.so --extern serde_json=/root/leaf/target/debug/deps/libserde_json-06ba15d2696b59f1.rmeta --extern sha1=/root/leaf/target/debug/deps/libsha1-5918fd781255ee3f.rmeta --extern sha2=/root/leaf/target/debug/deps/libsha2-8422c66d4f96c287.rmeta --extern sha3=/root/leaf/target/debug/deps/libsha3-3707bffba74dd508.rmeta --extern thiserror=/root/leaf/target/debug/deps/libthiserror-ce95d6a9e1059898.rmeta --extern tokio=/root/leaf/target/debug/deps/libtokio-d56861ee9f36647a.rmeta --extern tokio_rustls=/root/leaf/target/debug/deps/libtokio_rustls-bf5adc29062adbd8.rmeta --extern tokio_tungstenite=/root/leaf/target/debug/deps/libtokio_tungstenite-b251ef54b2cbefd7.rmeta --extern tokio_util=/root/leaf/target/debug/deps/libtokio_util-4185d767f79f0f5f.rmeta --extern trust_dns_proto=/root/leaf/target/debug/deps/libtrust_dns_proto-56586cbf0179f763.rmeta --extern tun=/root/leaf/target/debug/deps/libtun-b380ae75708e7ae2.rmeta --extern tungstenite=/root/leaf/target/debug/deps/libtungstenite-e87e8b5db0f97145.rmeta --extern url=/root/leaf/target/debug/deps/liburl-2b9971141a9f83ec.rmeta --extern uuid=/root/leaf/target/debug/deps/libuuid-0fbf32318de41ed2.rmeta --extern warp=/root/leaf/target/debug/deps/libwarp-415d78fffd7b7050.rmeta --extern webpki_roots=/root/leaf/target/debug/deps/libwebpki_roots-90e827deefd2f672.rmeta -L native=/root/leaf/target/debug/build/leaf-365acc5a411f410b/out -l static=lwip -L native=/root/leaf/target/debug/build/ring-efd1ee9212e3d1c7/out` (signal: 9, SIGKILL: kill)

以上是错误代码，无法编译成功，是否缺少什么组件

**Comment by eycorsican** [comment]
我猜是内存不够

**Comment by CHORDTAAX** [comment]
内存够的，后面换成ubuntu顺利编译
