### ISSUE TITLE
can we have demos for macos, windows, android to use leaf?

### ISSUE THREAD

**Issue by partychen** [eycorsican/leaf#12]
Leaf is a great lib, so can we have demos for macos, windows, android to use leaf? Thanks.

**Comment by eycorsican** [comment]
The `leaf-bin` and `leaf-mobile` crates are good examples.

**Comment by sayhell** [comment]
Is there any example for android lib? Thanks.

**Comment by rurirei** [comment]
```kotlin
val native = context.applicationContext.nativeDir.absolutePath

val conf = context.applicationContext.getExternalDir(null).absolutePath + File.separator + "config.conf"

val leaf = native + File.separator + "leaf -c " + conf

thread.Start {
    Runtime.exec(leaf)
}
```
though leaf/tun2socks-bin is for only macos or linux, as you need to find another way to do this, recommend eycorsican/go-tun2socks or badvpn/tun2socks.

**Comment by sayhell** [comment]
Is there any possibility to add some JNI supports in leaf-mobile to make leaf-mobile support Android same as iOS?

**Comment by eycorsican** [comment]
It's possible to make leaf-mobile works on Android, it's not trivial but the steps are quite straightforward.

1. You will have `rust-tun` work on Android, the implementation is almost the same as the iOS one: https://github.com/meh/rust-tun/pull/22/commits/75d3ef72575316e98e18af1658c876c3cbee14c0

2. You will have to make some changes to leaf-mobile so it can be conditionally compiled for both Android and iOS

3. On Android, all outgoing sockets must be protected, there are roughly two ways, FFI and RPC, the later is relatively easier: https://github.com/shadowsocks/shadowsocks-rust/blob/d6e2cee019c5c21e67c9c4a30d7c49d7ef7ba31b/src/relay/sys/unix/mod.rs#L38

**Comment by MoriarTy3zZ** [comment]
@eycorsican 您好，请问您 android 端 demo是否能分享一下？
