### ISSUE TITLE
[Bug Report]Can't set absolute site.dat path on Windows

### ISSUE THREAD

**Issue by perqin** [eycorsican/leaf#124]
I'm trying to add the `EXTERNAL` rules support to [Maple](https://github.com/YtFlow/Maple), and I find that there's some problem in Leaf's parsing the rule.

```rust
pub fn load_file_or_default(filter: &str, default: &str) -> Result<(String, String)> {
    let parts: Vec<&str> = filter.split(':').collect();
    let (file, code) = if parts.len() == 3 {
      // ...
    }
}
```

The code above gets the path in EXTERNAL rule by splitting `:`. When it comes to Windows, absolute path won't work because the `:` comes after the drive letter:

```
EXTERNAL site:C:\Users\Perqin\geosite.dat:cn, Direct
```

Though we can simply concatenate the `parts[2]` and `parts[3]` if `parts.len() == 4`, I'm wondering if there's better way to solve this issue.

**Comment by eycorsican** [comment]
> parts[2] and parts[3] if parts.len() == 4

I would be fine with this. Perhaps @bdbai has better  ideas?

**Comment by bdbai** [comment]
Maybe you drop the first and the last element in `parts` and join whatever in the middle by `:` to get the path? I am not sure if any more colons may appear after the path.

**Comment by eycorsican** [comment]
There would be no more than 3 components here.

**Comment by bdbai** [comment]
What if there is a comma followed by a space in the path, say `C:\Users\Perqin\geosite, enhanced.dat`?

**Comment by eycorsican** [comment]
Quotes? Commas are rare in file paths, I do want to cover these edge cases, there can be more discussions on this subject.

**Comment by bdbai** [comment]
One more reasonable way is to introduce a parser framework like `nom` or `lalrpop` so that these edge cases could be handled gracefully, but it requires a rewrite of current parser implementation.

**Comment by eycorsican** [comment]
FYI,

You don't always have to use an absolute path, there's an env var ASSET_LOCATION to specify where these resource files located.

**Comment by bdbai** [comment]
> You don't always have to use an absolute path, there's an env var ASSET_LOCATION to specify where these resource files located.

This must be useful. Thanks @eycorsican !

@perqin If we manage to set the value of this environment variable to the config path dynamically, everything would be easier. What do you think?

**Comment by perqin** [comment]
@bdbai This solution looks good. We could ask the user to pick multiple *.dat/*.mmdb files and copy them into Maple's app data directory, and then set `ASSET_LOCATION`'s value to that location. The only question is that whether its possible to set the env vars on calling `run_leaf`.

**Comment by bdbai** [comment]
@perqin Exactly. Even if env vars won't work, we can still add more arguments and adjust configuration ad-hoc just like how we deal with default interfaces.

**Comment by perqin** [comment]
@bdbai The env vars might not work, as Leaf is compiled as a static lib. Adjust configuration ad-hoc should work.

**Comment by bdbai** [comment]
@perqin Could explain a bit why env vars do not work with static libs?

**Comment by perqin** [comment]
The Leaf code is running in the same process as the Maple, right? I am not sure whether it is possible to set env vars within the process itself.

**Comment by DuckSoft** [comment]
It would be better if there are some FFI about this.

**Comment by cielpy** [comment]
macOS have system API to do this, https://github.com/eycorsican/leaf/issues/115#issuecomment-815586072 , maybe Windows has some API like this?

**Comment by bdbai** [comment]
@perqin 

> The Leaf code is running in the same process as the Maple

To be exact, the Leaf runtime is executed inside the VPN Plugin process, not the UI process.

>  I am not sure whether it is possible to set env vars within the process itself.

Feel free to have a try😂 The following code gives expected outputs on my machine.
```c++
    wchar_t v[100];
    if (GetEnvironmentVariable(L"MY_VAR", v, 100)) { // eval to false
        OutputDebugString(v);
    }
    if (!SetEnvironmentVariable(L"MY_VAR", L"MY_VALUE")) { // eval to true
        OutputDebugString(L"Cannot write env var");
    }
    if (GetEnvironmentVariable(L"MY_VAR", v, 100)) {
        OutputDebugString(v); // outputs `MY_VALUE`
    }
```

**Comment by perqin** [comment]
> Feel free to have a try😂 The following code gives expected outputs on my machine.

@bdbai Wow, I didn't know that before.

> Btw shall we continue Maple-specific discussion in the Maple repository?

Sure, I'm closing this issue, as it looks like that we needn't modify Leaf's code.
