### ISSUE TITLE
[bug]start leaf failed: handler not exists

### ISSUE THREAD

**Issue by cielpy** [eycorsican/leaf#125]
```
[Proxy Group]
Fallback=fallback, x1.0香港-中转1, x1.0香港-中转2, x1.0香港-中转3, x1.0香港-中转4, x1.0香港-中转5, x1.0香港-中转6, x1.0香港1, x1.0香港2, x1.0香港3, x1.0香港4, x1.0香港5, x1.0香港6, 香港丨专线丨HKBN丨1x, 香港丨专线丨HGC丨1x, 香港丨专线丨NTT丨1x, interval=600, timeout=5
Select=select, x1.0香港-中转1, x1.0香港-中转2, x1.0香港-中转3, x1.0香港-中转4, x1.0香港-中转5, x1.0香港-中转6, x1.0香港1, x1.0香港2, x1.0香港3, x1.0香港4, x1.0香港5, x1.0香港6, 香港丨专线丨HKBN丨1x, 香港丨专线丨HGC丨1x, 香港丨专线丨NTT丨1x
Proxy=select, Select, Fallback
[Rule]

EXTERNAL, site:category-ads-all, Reject
GEOIP,cn, Direct
FINAL, Proxy
```

After https://github.com/eycorsican/leaf/commit/b2b26d58b938b073429f125834799e5c5e9b132f , start with above config will fail, maybe because a select group in another select group.

**Comment by cielpy** [comment]
This commit https://github.com/eycorsican/leaf/commit/148efbc4940e7da42ad24d4bd61fb45cd2d75396 fixed this issue but when starting with no selector cache, it will still fail. @eycorsican

**Comment by eycorsican** [comment]
dev branch should have this issue fixed.
