### ISSUE TITLE
[Feature Request] IPv6 Support

### ISSUE THREAD

**Issue by waynon** [eycorsican/leaf#126]
Currently Leaf does not support IPv6 address, please add IPv6 support, which is very useful in CERNET. 

Without Leaf supporting IPv6, Maple and a lot of softwares based on Leaf can not add support for IPv6.

Also see https://github.com/eycorsican/leaf/issues/13

**Comment by eycorsican** [comment]
There are some progress on the dev branch.

**Comment by cielpy** [comment]
I have IPv6 environment, I can help test this feature if needed.

**Comment by eycorsican** [comment]
@cielpy Thanks, I look forward to hearing from you!

**Comment by foobartech** [comment]
Found two ipv6 issues with leaf-v0.3.1
1. ipv6 ip address `"address": "2a01:xxx:xxx:xx:xx::11"` is claimed invalid `[DEBUG] dispatch tcp 127.0.0.1:40964 -> google.com:80 to [] failed: invalid remote address: [2a01:xxx:xxx:xx:xx::11]:3001`
2. ipv6 domain address `"address": "ipv6.example.com"` can't be resovled while `nslookup ipv6.example.com` is ok

**Comment by waynon** [comment]
I've tested this feature. IPv6 support is now working as expected.

**Comment by eycorsican** [comment]
Please note IPv6 is disabled by  default and can be enabled by the `ENABLE_IPV6=true` environment variable, see https://github.com/eycorsican/leaf/blob/master/leaf/src/option/mod.rs for more supported env vars.

**Comment by wintrue** [comment]
> `ENABLE_IPV6=true`请注意 IPv6 默认情况下处于禁用状态，可以通过环境变量启用，请参阅https://github.com/eycorsican/leaf/blob/master/leaf/src/option/mod.rs了解更多受支持的环境变量。

windows下我添加了环境变量，但还是不行
