### ISSUE TITLE
support ipv6 and customized host 

### ISSUE THREAD

**Issue by acc557** [eycorsican/leaf#13]

**Comment by eycorsican** [comment]
You should be able to use IP addresses in all those outbounds.

**Comment by acc557** [comment]
It seems that I can not use IP address on VMESS over websockets, even if I set correct SNI. The domain name sent to the server seems to be overridden by the address.

**Comment by acc557** [comment]
I can use host file to create a record for the IP address as a workaround. But it's hard to do this on android. 
Would be great if leaf could provide separated configuration for "address" and "domain", or provide a internal host configuration for specifying the address for outbound.

**Comment by acc557** [comment]
Here it gets domain name 

https://github.com/eycorsican/leaf/blob/705aae52fe1817a8e178f9cc62a306f139747b71/leaf/src/proxy/tls/tcp.rs#L35

But here it seems to get ip

https://github.com/eycorsican/leaf/blob/master/leaf/src/proxy/ws/tcp.rs#L37

**Comment by acc557** [comment]
Same problem also applies to Trojan without tls,

https://github.com/eycorsican/leaf/blob/master/leaf/src/proxy/trojan/tcp.rs#L45

I also tried Trojan with tls, but it doesn't work either. Haven't figure out where could be the problem.

**Comment by eycorsican** [comment]
Show me your config.

**Comment by acc557** [comment]
```
{
    "log": {
        "level": "debug"
    },
    "dns": {
        "servers": [
            "1.1.1.1",
            "8.8.8.8"
        ]
    },
    "inbounds": [
        {
            "listen": "127.0.0.1",
            "port": 1087,
            "protocol": "http"
        },
        {
            "listen": "127.0.0.1",
            "port": 7890,
            "protocol": "socks",
            "settings": {
                "bind": "127.0.0.1"
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "failover",
            "settings": {
                "actors": [
                    "vmess_out",
                    "trojan_out"
                ]
            },
            "tag": "failover_out"
        },
        {
            "protocol": "chain",
            "settings": {
                "actors": [
                    "vmess_tls",
                    "vmess_ws",
                    "vmess"
                ]
            },
            "tag": "vmess_out"
        },
        {
            "protocol": "tls",
            "tag": "vmess_tls",
            "settings": {
                "serverName": "server.com",
                "host": "server.com",
                "alpn": ["http/1.1"]
            }
        },
        {
            "protocol": "ws",
            "settings": {
                "host": "server.com",
                "path": "/ws"
            },
            "tag": "vmess_ws"
        },
        {
            "protocol": "vmess",
            "settings": {
                "address": "2001:1234:1234::1",
                "port": 443,
                "uuid": "pwd"
            },
            "tag": "vmess"
        },
        {
            "protocol": "chain",
            "settings": {
                "actors": [
                    "trojan_tls",
                    "trojan"
                ]
            },
            "tag": "trojan_out"
        },
        {
            "protocol": "tls",
            "tag": "trojan_tls"
        },
        {
            "protocol": "trojan",
            "settings": {
                "address": "2001:1234:1234::1",
                "password": "pwd",
                "port": 443
            },
            "tag": "trojan"
        },
       
        {
            "protocol": "direct",
            "tag": "direct_out"
        },
        {
            "protocol": "drop",
            "tag": "drop_out"
        }
    ],
    "rules": [
        {
            "ip": [
                "8.8.8.8",
                "8.8.4.4"
            ],
            "target": "failover_out"
        }
    ]
}
```

**Comment by acc557** [comment]
Replacing `2001:1234:1234::1` to `server.com` will make websocket work again.

**Comment by acc557** [comment]
It seems that only h2 support hosts

https://github.com/eycorsican/leaf/blob/705aae52fe1817a8e178f9cc62a306f139747b71/leaf/src/proxy/h2/tcp.rs#L93
https://github.com/eycorsican/leaf/blob/705aae52fe1817a8e178f9cc62a306f139747b71/leaf/src/proxy/ws/tcp.rs#L19

also, the DNS of leaf can not resolve a AAAA-only response. even if I put the domain name that is ipv6-only in the address directly, it will still stuck at resolving address

**Comment by eycorsican** [comment]
Leaf does not yet support IPv6.

https://github.com/eycorsican/leaf/blob/6a82ee9b89cb19e5ee871667fd1480f60b5b80ff/leaf/src/proxy/mod.rs#L95

https://github.com/eycorsican/leaf/blob/6a82ee9b89cb19e5ee871667fd1480f60b5b80ff/leaf/src/common/dns_client.rs#L95

Taking h2 as an example, adding headers support in ws transport should be trivial.

**Comment by acc557** [comment]
OK. BTW do you have  any plans to support VMESS AEAD or VLESS?

**Comment by eycorsican** [comment]
No plans, but I welcome any PRs.

The plain VLESS protocol is already supported.
