### ISSUE TITLE
outbounds socks 无法连接网络, unexpected end of file

### ISSUE THREAD

**Issue by Jumptidus** [eycorsican/leaf#137]
配置是这样的，使用的socks

iPhone 12
iOS: 14.0
Xcode: Version 12.4 (12D4e)

使用ileaf demo构建, leaf版本latest

不能正常访问网络，查看日志都是unexpected end of file
网络方面的新手，抱歉无法调试，麻烦作者了。

不管怎样先谢谢了

`"""
[General]
loglevel = trace
dns-server = 223.5.5.5, 114.114.114.114
tun-fd = REPLACE-ME-WITH-THE-FD
routing-domain-resolve = true

interface = 127.0.0.1
port = 1087

socks-interface = 127.0.0.1
socks-port = 1086

[Proxy]
Direct = direct
Socks = socks, 60.185.35.143, 4234
[Rule]
FINAL, Socks
"""`

相对完整的日志
[connected]
Apr 16 15:49:46 PacketTunnel(PlugInKit)[973] <Notice>: Hello, I'm launching as euid = 501, uid = 501, personaid = 1000, type = DEFAULT, name = <private>
Apr 16 15:49:46 PacketTunnel(RunningBoardServices)[973] <Notice>: Initializing connection
Apr 16 15:49:46 PacketTunnel(RunningBoardServices)[973] <Notice>: Removing all cached process handles
Apr 16 15:49:46 PacketTunnel(RunningBoardServices)[973] <Notice>: Sending handshake request attempt #1 to server
Apr 16 15:49:46 PacketTunnel(RunningBoardServices)[973] <Notice>: Creating connection to com.apple.runningboard
Apr 16 15:49:46 PacketTunnel(RunningBoardServices)[973] <Notice>: Handshake succeeded
Apr 16 15:49:46 PacketTunnel(RunningBoardServices)[973] <Notice>: Identity resolved as xpcservice<com.proxy.Tidus.PacketTunnel([daemon<com.apple.neagent-ios>:362:362])>
Apr 16 15:49:46 PacketTunnel(PlugInKit)[973] <Notice>: Bootstrapping; Bootstrap complete. Ready for handshake from host.
Apr 16 15:49:46 PacketTunnel(PlugInKit)[973] <Notice>: [u 42A46BEA-A519-494A-97DF-112F3A533B66] [(null)((null))] Prepare received as euid = 501, uid = 501, personaid = 1000, type = DEFAULT, name = <private>
Apr 16 15:49:46 PacketTunnel(PlugInKit)[973] <Notice>: [u 3129C4D4-97AC-448E-8BBD-BCEAF6C42E2B] [<private>(<private>)] Set sole personality.
Apr 16 15:49:46 PacketTunnel(PlugInKit)[973] <Notice>: [u 3129C4D4-97AC-448E-8BBD-BCEAF6C42E2B] [<private>(<private>)] Begin using received as euid = 501, uid = 501, personaid = 1000, type = DEFAULT, name = <private>
Apr 16 15:49:46 PacketTunnel(libnetwork.dylib)[973] <Notice>: networkd_settings_read_from_file initialized networkd settings by reading plist directly
Apr 16 15:49:46 PacketTunnel(libnetwork.dylib)[973] <Notice>: networkd_settings_read_from_file initialized networkd settings by reading plist directly
Apr 16 15:49:46 PacketTunnel(libnetwork.dylib)[973] <Notice>: nw_path_evaluator_start [CF70B06D-EA67-4B65-9D68-5B2460E06039 <NULL> generic, indefinite]
	path: satisfied (Path is satisfied), interface: en0, ipv4, dns
Apr 16 15:49:46 PacketTunnel(NetworkExtension)[973] <Notice>: [Extension com.proxy.Tidus.PacketTunnel]: Calling startTunnelWithOptions with options 0x0
Apr 16 15:49:46 PacketTunnel(libsystem_containermanager.dylib)[973] <Notice>: Requesting app group container lookup; identifier = <private>, euid = 501, uid = 501, platform = 2, personaid = 1000, type = DEFAULT, name = 6DC99B67-CC32-4890-807A-9F0901A06073
Apr 16 15:49:46 PacketTunnel(libsystem_containermanager.dylib)[973] <Notice>: container_create_or_lookup_app_group_path_by_app_group_identifier: success
Apr 16 15:49:46 PacketTunnel[973] <Notice>: [2021-04-16 15:49:46][DEBUG] default handler [Socks]
Apr 16 15:49:46 PacketTunnel[973] <Notice>: [2021-04-16 15:49:46][INFO] inbound listening tcp 127.0.0.1:1086
Apr 16 15:49:46 PacketTunnel[973] <Notice>: [2021-04-16 15:49:46][INFO] inbound listening udp 127.0.0.1:1086
Apr 16 15:49:46 PacketTunnel[973] <Notice>: [2021-04-16 15:49:46][INFO] tun inbound started
Apr 16 15:49:46 PacketTunnel[973] <Notice>: [2021-04-16 15:49:46][INFO] inbound listening tcp 127.0.0.1:1087
Apr 16 15:49:46 PacketTunnel[973] <Notice>: [2021-04-16 15:49:46][DEBUG] allocate 240.255.0.0 for commnat-main-gc.ess.apple.com
Apr 16 15:49:46 PacketTunnel[973] <Notice>: [2021-04-16 15:49:46][DEBUG] allocate 240.255.0.1 for commnat-cohort-gc.ess.apple.com
Apr 16 15:49:46 PacketTunnel[973] <Notice>: [2021-04-16 15:49:46][DEBUG] added udp session 240.0.0.1:16403 -> 240.255.0.0:16384 (1)
Apr 16 15:49:46 PacketTunnel[973] <Notice>: [2021-04-16 15:49:46][TRACE] pick route failed: no matching rules
Apr 16 15:49:46 PacketTunnel[973] <Notice>: [2021-04-16 15:49:46][DEBUG] picked default route [Socks] for 240.0.0.1:16403 -> commnat-main-gc.ess.apple.com:16384
Apr 16 15:49:46 PacketTunnel[973] <Notice>: [2021-04-16 15:49:46][TRACE] dialing tcp 60.185.35.143:4234
Apr 16 15:49:46 PacketTunnel[973] <Notice>: [2021-04-16 15:49:46][TRACE] connected tcp 60.185.35.143:4234
Apr 16 15:49:47 PacketTunnel[973] <Notice>: [2021-04-16 15:49:47][DEBUG] allocate 240.255.0.2 for www.apple.com
Apr 16 15:49:47 PacketTunnel[973] <Notice>: [2021-04-16 15:49:47][DEBUG] allocate 240.255.0.3 for guzzoni.apple.com
Apr 16 15:49:47 PacketTunnel[973] <Notice>: [2021-04-16 15:49:47][DEBUG] allocate 240.255.0.4 for www.icloud.com
Apr 16 15:49:47 PacketTunnel[973] <Notice>: [2021-04-16 15:49:47][DEBUG] allocate 240.255.0.5 for p22-fmf.icloud.com.cn
Apr 16 15:49:47 PacketTunnel[973] <Notice>: [2021-04-16 15:49:47][DEBUG] allocate 240.255.0.6 for play.itunes.apple.com
Apr 16 15:49:47 PacketTunnel[973] <Notice>: [2021-04-16 15:49:47][DEBUG] dispatch udp 240.0.0.1:16403 -> commnat-main-gc.ess.apple.com:16384 to [Socks] failed: unexpected end of file
Apr 16 15:49:48 PacketTunnel[973] <Notice>: [2021-04-16 15:49:48][DEBUG] added udp session 240.0.0.1:16403 -> 240.255.0.0:16384 (1)
Apr 16 15:49:48 PacketTunnel[973] <Notice>: [2021-04-16 15:49:48][TRACE] pick route failed: no matching rules
Apr 16 15:49:48 PacketTunnel[973] <Notice>: [2021-04-16 15:49:48][DEBUG] picked default route [Socks] for 240.0.0.1:16403 -> commnat-main-gc.ess.apple.com:16384
Apr 16 15:49:48 PacketTunnel[973] <Notice>: [2021-04-16 15:49:48][TRACE] dialing tcp 60.185.35.143:4234
Apr 16 15:49:48 PacketTunnel[973] <Notice>: [2021-04-16 15:49:48][DEBUG] dispatch udp 240.0.0.1:16403 -> commnat-main-gc.ess.apple.com:16384 to [Socks] failed: all attempts failed, last error: connect failed: Connection refused (os error 61)

**Comment by eycorsican** [comment]
请把复现步骤列一下，包括但不限于客户端配置，服务端配置，请求发送方式。

**Comment by Jumptidus** [comment]
抱歉，搭建复现环境的时候，连接没有问题，应该是测试时服务器端的问题。
