### ISSUE TITLE
无法配置vmess协议的alterid字段

### ISSUE THREAD

**Issue by fwcde** [eycorsican/leaf#14]
作者您好，当前leaf版本似乎不支持自定义vmess协议的alterid字段？恳请新增支持，毕竟不少v2ray core服务端没有更新到最新版本，自带新版v2ray内核的客户端默认使用alterid=0将致使其无法正常工作。

**Comment by eycorsican** [comment]
alterid=0 means you are using VMess AEAD, and that's not yet supported in leaf.

**Comment by chuxubank** [comment]
proxy/vmess/encoding: Critical Warning: potentially invalid user: a non VMessAEAD connection is received. From 2022 Jan 1st, this kind of connection will be rejected by default. You should update or replace your client software now. This message will not be shown for further violation on this inbound.

**Comment by sbh96** [comment]
hi, same issue, when it's ready for alterid? we really need it
@eycorsican  don't close all issues let the team find and solve this issue 
without VMess AEAD you lose the biggest users coming from v2ray
