### ISSUE TITLE
iOS 用json不能运行

### ISSUE THREAD

**Issue by shagfu** [eycorsican/leaf#143]
我的json 内容如下 
let conf = """
{
    "log": {
        "level": "trace"
    },
    "dns": {
        "servers": [
            "223.5.5.5",
            "8.8.8.8"
        ]
    },
    "inbounds": [
        {
            "address": "127.0.0.1",
            "port": 1087,
            "protocol": "http"
        }
    ],
    "outbounds": [
        {
            "protocol": "direct",
            "tag": "direct_out"
        },
        {
            "protocol": "vmess",
            "settings": {
                "address": "30.43.120.182",
                "port": 30005,
                "uuid": "e02431b6-9e5a-11eb-a8b3-0242ac130003"
            },
            "tag": "vmess"
        },
        {
            "protocol": "shadowsocks",
            "settings": {
                "address": "30.43.120.182",
                "method": "aes-256-gcm",
                "password": "123456",
                "port": 30001
            },
            "tag": "shadowsocks_out"
        },
        {
            "protocol": "drop",
            "tag": "drop_out"
        }

    ],
    "rules": [
        {
            "domainKeyword": [
                "baidu"
            ],
            "target": "shadowsocks_out"
        },
        {
            "domain": [
                "www.baidu.com"
            ],
            "target": "shadowsocks_out"
        },
        {
            "external": [
                "site:cn"
            ],
            "target": "direct_out"
        }
    ]
}
然后在将 代码 改成如下
let url = FileManager().containerURL(forSecurityApplicationGroupIdentifier: appGroup)!.appendingPathComponent("running_config.json")
控制台输出 [INFO] inbound listening tcp 127.0.0.1:1087 
请问下json内容对吗？
同样的配置用conf 是可以的。

**Comment by eycorsican** [comment]
没看出什么问题，有监听 HTTP 的日志输出就应该 可以

**Comment by shagfu** [comment]
用conf 配置，输出  tun inbound started,用json 没有输出这条日志，是不是这个函数哪里出错了，json 里面tun-fd = REPLACE-ME-WITH-THE-FD这个 fd需要配置吗？
另外请问下conf http2 如何配置？
