### ISSUE TITLE
Bind  IPv6 Privicy Extention address, not SLAAC or DHCP address

### ISSUE THREAD

**Issue by cielpy** [eycorsican/leaf#147]
To protect privacy, IPv6 has [Privacy Extention](https://tools.ietf.org/html/rfc4941), at leaf's algorithm, leaf maybe bind an address that from DHCP server or SLAAC, for me, the address `240e:xxxx::55c`'s suffix `55c` is fixed, the prefix is get from ISP with DHCP-PD

```
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=40b<RXCSUM,TXCSUM,VLAN_HWTAGGING,CHANNEL_IO>
	ether e0:d5:5e:8c:2f:db
	inet6 fe80::45b:290d:690d:fa25%en0 prefixlen 64 secured scopeid 0x4
	inet 192.168.xxx.101 netmask 0xffffff00 broadcast 192.168.xxx.255
	inet6 240e:xxxx:833:fe8c:cb27:f36 prefixlen 64 autoconf secured pltime 1946 vltime 1946
	inet6 240e:xxxx:c8ca:8b67:792:de39 prefixlen 64 autoconf temporary pltime 1946 vltime 1946
	inet6 fd81:xxx:18ad:c533:e1ed:3d1e prefixlen 64 autoconf secured
	inet6 fd81:xxx:8dcf:51cf:fa4e:14ed prefixlen 64 autoconf temporary pltime 84336 vltime 602736
	inet6 240e:xxxx::55c prefixlen 64 dynamic pltime 1946 vltime 1946
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (1000baseT <full-duplex,flow-control>)
	status: active
```

`240e:xxxx:c8ca:8b67:792:de39` is the privacy address, change over time. with system network stack, this IP has higher priority to use, I think leaf should follow this rule.

**Comment by eycorsican** [comment]
It's [now](https://github.com/eycorsican/leaf/commit/c12c5d1688163122785d7ae2074eae7b63649090) up to the OS to choose the "right" address for you.

**Comment by cielpy** [comment]
> It's [now](https://github.com/eycorsican/leaf/commit/c12c5d1688163122785d7ae2074eae7b63649090) up to the OS to choose the "right" address for you.

Good job!
