### ISSUE TITLE
如何编译支持osx的libleaf.a？

### ISSUE THREAD

**Issue by wangjinwei0806** [eycorsican/leaf#149]
查看 libleaf-ios % lipo -info libleaf.a
Architectures in the fat file: libleaf.a are: arm64 

如何编译出支持支持Mac 的lib?

**Comment by cielpy** [comment]
make lib 即可 https://github.com/eycorsican/leaf/blob/master/Makefile#L9

**Comment by wangjinwei0806** [comment]
tks

**Comment by wangjinwei0806** [comment]
@cielpy  能正常编译   iOS的规则 Mac 没办法用，就是不能正常使用，不知道是不是规则路径的原因？

**Comment by cielpy** [comment]
> ASSET_LOCATION

ASSET_LOCATION 可以用，https://github.com/eycorsican/leaf/issues/115

**Comment by wangjinwei0806** [comment]
ASSET_LOCATION  写配置信息里面吗？我各种尝试都不行

**Comment by cielpy** [comment]
> ASSET_LOCATION 写配置信息里面吗？我各种尝试都不行

声明一个环境变量 https://github.com/eycorsican/leaf/issues/115#issuecomment-815586072

**Comment by wangjinwei0806** [comment]
不知道这个环境变量设置哪里路径比较合理，尝试归档，group ,本地静态路径都不行，要不就是没得权限，链接成功后，代理没成功
查看https://github.com/eycorsican/leaf/blob/master/leaf/src/option/mod.rs#L58这边，貌似是获取ASSET_LOCATION对应的环境变量值

**Comment by wangjinwei0806** [comment]
用leaf_test_config 测试相对路径规则 返回的是的是0，在传给leaf_run，如果设置tun-fd 等于具体某一个值，直接挂了，如果不设置这个值，不出现问题，但是代理没法用

**Comment by cielpy** [comment]
如果你用 Swift，调用 `leaf_run` 前调用 `setenv` 设置环境变量
```
setenv("ASSET_LOCATION", "/Users/xxx/xxx/", 1)
```

然后把资源文件放到 /Users/xxx/xxx/ 下就可以了

添加一条规则

```
EXTERNAL,site:category-ads-all,Reject
```

启动 leaf 日志里会有显示加载成功

```
loaded 639 domain rules from [/Users/xxx/xxx/site.dat] for tag [category-ads-all]
```

正常情况下，整个流程就是这样的了

**Comment by wangjinwei0806** [comment]
不行  已经测试过了

**Comment by cielpy** [comment]
我实测，是可以的

**Comment by wangjinwei0806** [comment]
> 我实测，是可以的

你用的是NE吗？

**Comment by cielpy** [comment]
> 不行 已经测试过了,我猜你用的是单机版
> 我是用的插件ne，这地方貌似不能直接用ne,tun-fd 这边貌似有点问题，如果用ne
> ![image](https://user-images.githubusercontent.com/3974508/115574291-13a17380-a2f4-11eb-8884-9c4c218ef7ce.png)

什么是单机版？

我没有用 NE，直接调用 leaf_run 运行的

用 NE leaf 应该是运行在另一个进程吧，setenv 应该是作用于当前进程

**Comment by wangjinwei0806** [comment]
> > 不行 已经测试过了,我猜你用的是单机版
> > 我是用的插件ne，这地方貌似不能直接用ne,tun-fd 这边貌似有点问题，如果用ne
> > ![image](https://user-images.githubusercontent.com/3974508/115574291-13a17380-a2f4-11eb-8884-9c4c218ef7ce.png)
> 
> 什么是单机版？
> 
> 我没有用 NE，直接调用 leaf_run 运行的
> 
> 用 NE leaf 应该是运行在另一个进程吧，setenv 应该是作用于当前进程

明白了 单机版是指那种不用通过苹果商店奋发的

**Comment by wangjinwei0806** [comment]
> 如果你用 Swift，调用 `leaf_run` 前调用 `setenv` 设置环境变量
> 
> ```
> setenv("ASSET_LOCATION", "/Users/xxx/xxx/", 1)
> ```
> 
> 然后把资源文件放到 /Users/xxx/xxx/ 下就可以了
> 
> 添加一条规则
> 
> ```
> EXTERNAL,site:category-ads-all,Reject
> ```
> 
> 启动 leaf 日志里会有显示加载成功
> 
> ```
> loaded 639 domain rules from [/Users/xxx/xxx/site.dat] for tag [category-ads-all]
> ```
> 
> 正常情况下，整个流程就是这样的了

 刚才测试了一下是这样的，用NE的话，设置本地路径 没得权限的，还发现一个问题，传入配置文件的路径中如果含有空格，传入leaf_run 会导致没办法找到相应的路径的，不知道这位开源大神有没有遇到过

**Comment by cielpy** [comment]
> > 如果你用 Swift，调用 `leaf_run` 前调用 `setenv` 设置环境变量
> > ```
> > setenv("ASSET_LOCATION", "/Users/xxx/xxx/", 1)
> > ```
> > 
> > 
> > 然后把资源文件放到 /Users/xxx/xxx/ 下就可以了
> > 添加一条规则
> > ```
> > EXTERNAL,site:category-ads-all,Reject
> > ```
> > 
> > 
> > 启动 leaf 日志里会有显示加载成功
> > ```
> > loaded 639 domain rules from [/Users/xxx/xxx/site.dat] for tag [category-ads-all]
> > ```
> > 
> > 
> > 正常情况下，整个流程就是这样的了
> 
> 刚才测试了一下是这样的，用NE的话，设置本地路径 没得权限的，还发现一个问题，传入配置文件的路径中如果含有空格，传入leaf_run 会导致没办法找到相应的路径的，不知道这位开源大神有没有遇到过

我没有搞过 NE 的开发，猜测 NE 应该是一个受限的沙盒进程，所以不能访问本地路径吧

没有遇到过，macOS 的路径有空格时需要处理吧，个人是尽量避免路径有空格的，所以没遇到

**Comment by wangjinwei0806** [comment]
start with options:
StartOptions {
    config: File(
        "/Users/xxxxxx/Library/Group Containers/xxxxxxtest/config.conf",
    ),
    runtime_opt: SingleThread,
}
loaded 629 domain rules from [/Users/xxxxxx/Library/Group Containers/xxxxxxtest/site.dat] for tag [category-ads-all]
loaded 2665 domain rules from [/Users/xxxxxx/Library/Group Containers/xxxxxxtest/site.dat] for tag [cn]
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" })', leaf/src/proxy/tun/inbound.rs:88:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

有遇到这种问题没

**Comment by nahddw** [comment]
@wangjinwei0806 老哥我也用NE测试的 但是无法启动PacketTunnel 日志里只找到这处看似有问题的地方
secinitd	PacketTunnel[9924]: root path for bundle "<private>" of main executable "<private>" 
你那边能正常启用吗？

**Comment by cielpy** [comment]
> start with options:
> StartOptions {
> config: File(
> "/Users/xxxxxx/Library/Group Containers/xxxxxxtest/config.conf",
> ),
> runtime_opt: SingleThread,
> }
> loaded 629 domain rules from [/Users/xxxxxx/Library/Group Containers/xxxxxxtest/site.dat] for tag [category-ads-all]
> loaded 2665 domain rules from [/Users/xxxxxx/Library/Group Containers/xxxxxxtest/site.dat] for tag [cn]
> thread '' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" })', [leaf/src/proxy/tun/inbound.rs:88:42](https://github.com/eycorsican/leaf/blob/master/leaf/src/proxy/tun/inbound.rs#L88)
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> 有遇到这种问题没，用NE 用到tun-fd 就挂了

@wangjinwei0806 没有权限，日志里说的很清楚了

**Comment by wangjinwei0806** [comment]
> > start with options:
> > StartOptions {
> > config: File(
> > "/Users/xxxxxx/Library/Group Containers/xxxxxxtest/config.conf",
> > ),
> > runtime_opt: SingleThread,
> > }
> > loaded 629 domain rules from [/Users/xxxxxx/Library/Group Containers/xxxxxxtest/site.dat] for tag [category-ads-all]
> > loaded 2665 domain rules from [/Users/xxxxxx/Library/Group Containers/xxxxxxtest/site.dat] for tag [cn]
> > thread '' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" })', [leaf/src/proxy/tun/inbound.rs:88:42](https://github.com/eycorsican/leaf/blob/master/leaf/src/proxy/tun/inbound.rs#L88)
> > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > 有遇到这种问题没，用NE 用到tun-fd 就挂了
> 
> @wangjinwei0806 没有权限，日志里说的很清楚了

我知道是没得权限，但是leaflib 这个框架怎么给权限，这个需要如何操作，报错这个不是用的NE，按照你上面描述的设置setenv 环境变量，后面直接出现上面这个错误了，是不是使用方式不对，“loaded 629 domain rules ”有这些日志了，説名路径正常

**Comment by cielpy** [comment]
> > > start with options:
> > > StartOptions {
> > > config: File(
> > > "/Users/xxxxxx/Library/Group Containers/xxxxxxtest/config.conf",
> > > ),
> > > runtime_opt: SingleThread,
> > > }
> > > loaded 629 domain rules from [/Users/xxxxxx/Library/Group Containers/xxxxxxtest/site.dat] for tag [category-ads-all]
> > > loaded 2665 domain rules from [/Users/xxxxxx/Library/Group Containers/xxxxxxtest/site.dat] for tag [cn]
> > > thread '' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" })', [leaf/src/proxy/tun/inbound.rs:88:42](https://github.com/eycorsican/leaf/blob/master/leaf/src/proxy/tun/inbound.rs#L88)
> > > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > > 有遇到这种问题没，用NE 用到tun-fd 就挂了
> > 
> > 
> > @wangjinwei0806 没有权限，日志里说的很清楚了
> 
> 我知道是没得权限，但是leaflib 这个框架怎么给权限，这个需要如何操作，报错这个不是用的NE，按照你上面描述的设置setenv 环境变量，后面直接出现上面这个错误了，是不是使用方式不对，“loaded 629 domain rules ”有这些日志了，説名路径正常

这个需要你自己结合 NE 文档查了，我并不清楚，抱歉

**Comment by wangjinwei0806** [comment]
上面的没用NE，你在运行lib的时候有遇到以下日志吗？
start with options:
StartOptions {
    config: File(
        "/Users/xxxxxxx/Library/Developer/Xcode/DerivedData/testleaf-ewmwyppsbjyxhrbrzvhgllacauzj/Build/Products/Debug/testleaf.app/Contents/Resources/config.conf",
    ),
    runtime_opt: SingleThread,
}
loaded 629 domain rules from [/Users/xxxxxxx/Library/Developer/Xcode/DerivedData/testleaf-ewmwyppsbjyxhrbrzvhgllacauzj/Build/Products/Debug/testleaf.app/Contents/Resources/site.dat] for tag [category-ads-all]
loaded 2665 domain rules from [/Users/xxxxxxx/Library/Developer/Xcode/DerivedData/testleaf-ewmwyppsbjyxhrbrzvhgllacauzj/Build/Products/Debug/testleaf.app/Contents/Resources/site.dat] for tag [cn]
[33m[2021-04-22 18:18:45][[33mWARN[0m[33m] open mmdb file /Users/xxxxxxx/Library/Developer/Xcode/DerivedData/testleaf-ewmwyppsbjyxhrbrzvhgllacauzj/Build/Products/Debug/testleaf.app/Contents/Resources/mmdb failed[0m
[33m[2021-04-22 18:18:45][[33mWARN[0m[33m] empty rule at target Direct[0m
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" })', leaf/src/proxy/tun/inbound.rs:88:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by cielpy** [comment]
> 上面的没用NE，你在运行lib的时候有遇到以下日志吗？
> 
> start with options:
> 
> StartOptions {
> 
>     config: File(
> 
>         "/Users/xxxxxxx/Library/Developer/Xcode/DerivedData/testleaf-ewmwyppsbjyxhrbrzvhgllacauzj/Build/Products/Debug/testleaf.app/Contents/Resources/config.conf",
> 
>     ),
> 
>     runtime_opt: SingleThread,
> 
> }
> 
> loaded 629 domain rules from [/Users/xxxxxxx/Library/Developer/Xcode/DerivedData/testleaf-ewmwyppsbjyxhrbrzvhgllacauzj/Build/Products/Debug/testleaf.app/Contents/Resources/site.dat] for tag [category-ads-all]
> 
> loaded 2665 domain rules from [/Users/xxxxxxx/Library/Developer/Xcode/DerivedData/testleaf-ewmwyppsbjyxhrbrzvhgllacauzj/Build/Products/Debug/testleaf.app/Contents/Resources/site.dat] for tag [cn]
> 
> [33m[2021-04-22 18:18:45][[33mWARN[0m[33m] open mmdb file /Users/xxxxxxx/Library/Developer/Xcode/DerivedData/testleaf-ewmwyppsbjyxhrbrzvhgllacauzj/Build/Products/Debug/testleaf.app/Contents/Resources/mmdb failed[0m
> 
> [33m[2021-04-22 18:18:45][[33mWARN[0m[33m] empty rule at target Direct[0m
> 
> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" })', leaf/src/proxy/tun/inbound.rs:88:42
> 
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Xcode scheme 里，调整成用root用户运行

**Comment by wangjinwei0806** [comment]
![image](https://user-images.githubusercontent.com/3974508/115702467-8e719980-a39b-11eb-839c-9f3749891d70.png)
一样的问题

**Comment by wangjinwei0806** [comment]
start with options:
StartOptions {
    config: File(
        "/var/root/Library/Developer/Xcode/DerivedData/testleaf-ewmwyppsbjyxhrbrzvhgllacauzj/Build/Products/Debug/testleaf.app/Contents/Resources/config.conf",
    ),
    runtime_opt: SingleThread,
}
loaded 629 domain rules from [/var/root/Library/Developer/Xcode/DerivedData/testleaf-ewmwyppsbjyxhrbrzvhgllacauzj/Build/Products/Debug/testleaf.app/Contents/Resources/site.dat] for tag [category-ads-all]
loaded 2665 domain rules from [/var/root/Library/Developer/Xcode/DerivedData/testleaf-ewmwyppsbjyxhrbrzvhgllacauzj/Build/Products/Debug/testleaf.app/Contents/Resources/site.dat] for tag [cn]
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 16, kind: Other, message: "Resource busy" })', leaf/src/proxy/tun/inbound.rs:88:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

"Resource busy" 资源被占用，我重启电脑还是这样

**Comment by cielpy** [comment]
是不是有另一个 leaf 进程在跑而且用的相同的配置文件？资源有竞争了？

**Comment by eycorsican** [comment]
提供一下完整调用代码和 配置
