### ISSUE TITLE
osx 非NE,dmg版

### ISSUE THREAD

**Issue by wangjinwei0806** [eycorsican/leaf#158]
mac 网络->高级->代理 勾选了 https/http/socks 代理和配置文件代理一致

打开商店版tg的,不使用tg自带的代理功能，出现以下日志错误信息，打开tg自带的代理，可以正常连接

[37m[2021-04-23 19:58:34][[37mDEBUG[0m[37m] accept conn failed: invalid HTTP method parsed[0m
[37m[2021-04-23 19:58:34][[37mDEBUG[0m[37m] handle inbound tcp failed: Custom { kind: Other, error: "unspecified" }[0m
[37m[2021-04-23 19:58:34][[37mDEBUG[0m[37m] accept conn failed: invalid HTTP method parsed[0m
[37m[2021-04-23 19:58:34][[37mDEBUG[0m[37m] handle inbound tcp failed: Custom { kind: Other, error: "unspecified" }[0m
[37m[2021-04-23 19:58:34][[37mDEBUG[0m[37m] accept conn failed: invalid HTTP method parsed[0m
[37m[2021-04-23 19:58:34][[37mDEBUG[0m[37m] handle inbound tcp failed: Custom { kind: Other, error: "unspecified" }[0m

**Comment by wangjinwei0806** [comment]
tun 网卡是不是要自己创建 @cielpy ，如果不是用NE的话

**Comment by zhangyuge** [comment]
用这是不是NE上行不通？

**Comment by cielpy** [comment]
> tun 网卡是不是要自己创建 @cielpy ，如果不是用NE的话
> 
> 第一次调leaf_run，接着关闭调leaf_shutdown，接着再次调leaf_run
> 出现以下错误日志
> 
> thread '' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 25, kind: Other, message: "Inappropriate ioctl for device" })', leaf/src/proxy/tun/inbound.rs:88:42
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

需要自己创建，不过不用在 leaf_run 时候创建，设置路由表的时候一起创建就行了，leaf 现在有自动配置路由表模式，设置 tun=auto 就可以了，运行的命令在 https://github.com/eycorsican/leaf/blob/10e600d27db13d0aada6917c3df9ad4afec5cf40/leaf/src/common/cmd_macos.rs

**Comment by wangjinwei0806** [comment]
> 用这是不是NE上行不通？



> 用这是不是NE上行不通？

行的通的

**Comment by wangjinwei0806** [comment]
> > tun 网卡是不是要自己创建 @cielpy ，如果不是用NE的话
> > 第一次调leaf_run，接着关闭调leaf_shutdown，接着再次调leaf_run
> > 出现以下错误日志
> > thread '' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 25, kind: Other, message: "Inappropriate ioctl for device" })', leaf/src/proxy/tun/inbound.rs:88:42
> > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> 需要自己创建，不过不用在 leaf_run 时候创建，设置路由表的时候一起创建就行了，leaf 现在有自动配置路由表模式，设置 tun=auto 就可以了，运行的命令在 https://github.com/eycorsican/leaf/blob/10e600d27db13d0aada6917c3df9ad4afec5cf40/leaf/src/common/cmd_macos.rs

謝謝 已經測試成功

**Comment by wangjinwei0806** [comment]
@cielpy  如何正常的关闭之前调用leaf_run的方法
我尝试调用调用leaf_run方法之前关闭，调用leaf_shutdown，有的时候会出现以下日志
//[37m[2021-04-27 10:11:37][[37mDEBUG[0m[37m] default handler [Fallback][0m
//[90m[2021-04-27 10:11:37][[90mTRACE[0m[90m] add handler [Direct][0m
//[90m[2021-04-27 10:11:37][[90mTRACE[0m[90m] add handler [Reject][0m
//[90m[2021-04-27 10:11:37][[90mTRACE[0m[90m] add handler [vmess-out_tls_xxx][0m
//[90m[2021-04-27 10:11:37][[90mTRACE[0m[90m] add handler [vmess-out_ws_xxx][0m
//[90m[2021-04-27 10:11:37][[90mTRACE[0m[90m] add handler [vmess-out_vmess_xxx][0m
//[90m[2021-04-27 10:11:37][[90mTRACE[0m[90m] add handler [vmess-out] with actors: vmess-out_tls_xxx,vmess-out_ws_xxx,vmess-out_vmess_xxx[0m
//[90m[2021-04-27 10:11:37][[90mTRACE[0m[90m] add handler [Fallback] with actors: vmess-out[0m
//thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', leaf/src/common/cmd_macos.rs:66:10
//note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by cielpy** [comment]
没遇到过，你可以看一下 leaf崩溃信息，看看那一行做了什么

**Comment by zhangyuge** [comment]
请问下NE版本是不是不能打包DeveloperID？非NE怎么使用这库呢？
