### ISSUE TITLE
如何开启全局代理

### ISSUE THREAD

**Issue by xingdaos** [eycorsican/leaf#160]
我看了下详情配置，都是 inbounds 和 outbounds ，全是端口代理，有办法全局代理吗

**Comment by FlyGGYe** [comment]
> 我看了下详情配置，都是 inbounds 和 outbounds ，全是端口代理，有办法全局代理吗

你把outbounds的代理的配置配置到第一个上。然后不给他路由规则。就会全部走代理了

**Comment by tonyling99** [comment]
conf 文件怎么配置，出站只看到json 文件有这玩意
