### ISSUE TITLE
作者您好

### ISSUE THREAD

**Issue by FlyGGYe** [eycorsican/leaf#162]
我发现leaf跑trojan在iOS上速度很慢。只有100-300，看youtube的时候，但其他可以跑到5000以上。我看了半天没看出哪里有问题。为此我还下了很多老包做测试。0.2.7没有这个问题

**Comment by FlyGGYe** [comment]
[debug.log](https://github.com/eycorsican/leaf/files/6381140/debug.log)
日志在这

**Comment by FlyGGYe** [comment]
![image](https://user-images.githubusercontent.com/46473120/116168486-11e11100-a735-11eb-99ca-32d8cecd8bb3.png)
服务端日志是这样的

**Comment by LaoHuan** [comment]
请问你的问题解决了吗？怎么解决的？

**Comment by FlyGGYe** [comment]
> 请问你的问题解决了吗？怎么解决的？

没解决。等待作者解决

**Comment by a497500306** [comment]
你的trojan配置怎么配置的？我这边一直链接不上，能留个联系方式一起交流一下吗？

**Comment by StaticNonautomatic** [comment]
Any luck finding the solution?
