### ISSUE TITLE
How to bypass local?

### ISSUE THREAD

**Issue by giftedunicorn** [eycorsican/leaf#167]
I tried this in config.conf, and it's not working. Local address is still going through proxy

[Rule]
IP-CIDR, 0.0.0.0/8, Direct
IP-CIDR, 10.0.0.0/8, Direct
IP-CIDR, 100.64.0.0/10, Direct
IP-CIDR, 127.0.0.0/8, Direct
IP-CIDR, 169.254.0.0/16, Direct
IP-CIDR, 172.16.0.0/12, Direct
IP-CIDR, 192.0.0.0/24, Direct
IP-CIDR, 192.0.2.0/24, Direct
IP-CIDR, 192.88.99.0/24, Direct
IP-CIDR, 192.168.1.207, Direct
IP-CIDR, 192.168.0.0/16, Direct
IP-CIDR, 198.18.0.0/15, Direct
IP-CIDR, 198.51.100.0/24, Direct
IP-CIDR, 203.0.113.0/24, Direct
IP-CIDR, 224.0.0.0/4, Direct
IP-CIDR, 240.0.0.0/4, Direct
IP-CIDR, 255.255.255.255/32, Direct
IP-CIDR, ::1/128, Direct
IP-CIDR, fc00::/7, Direct
IP-CIDR, fe80::/10, Direct
FINAL, Proxy

**Comment by giftedunicorn** [comment]
It works

**Comment by giftedunicorn** [comment]
routing-domain-resolve = true

**Comment by 2856571872** [comment]
> routing-domain-resolve = true

请问有没有conf配置教程，这个好像和其他的差距挺大
