### ISSUE TITLE
The Issue with Trojan Uploading

### ISSUE THREAD

**Issue by giftedunicorn** [eycorsican/leaf#171]
When I use Leaf Trojan to test on speedtest, the download will reach 200+Mbps, but the upload will reach 30+Mbps and drop to 1Mbps immediately. 

When I use Leaf SS to test on speedtest, the download will reach 200+Mbps, the upload will reach 30+Mbps and remain the speed until it's finished testing. 

When I use Trojan-qt5 and same Trojan server to test on speedtest, the download will reach 200+Mbps, the upload will reach 30+Mbps and remain the speed until it's finished testing. 

When I use WireShark to check the activities, I see there are tons of TCP Out of Order, TCP Dup Ack and TCP retransmission when it's uploading. 

I use Macbook and all tests are done in outside of China. I see there are several issues talking about the uploading issue. When they upload videos or images to YouTube or Instagram, it will stuck. 

Hope this can help. I wish i know more in rust.

**Comment by eycorsican** [comment]
Please reproduce the issue with leaf as the server implementation and provide all the software versions, configurations and logs.

**Comment by giftedunicorn** [comment]
I found out set TCP_UPLINK_TIMEOUT from 2s to 4s will fix this uplink problem. Is it safe to change this value to 4?

**Comment by giftedunicorn** [comment]
What I found is that the local debug build (cargo build -p leaf-bin) has no problem with upload.

But the production build (download from github release) will have problem with upload.

I tested with the a46e300 build

**Comment by giftedunicorn** [comment]
[General]
loglevel = info
dns-server = 8.8.8.8
socks-interface = 127.0.0.1
socks-port = 1080

[Proxy]
Direct = direct
Proxy = trojan, 12.12.12.12, 443, password=123123123, sni=example.com

[Rule]
FINAL, Proxy

**Comment by giftedunicorn** [comment]
When try to upload video to youtube, it will stuck and show this error:
[2021-05-09 18:18:28][DEBUG] tcp downlink 127.0.0.1:49651 <- upload.youtube.com:443 timeout: deadline has elapsed [Proxy]

It can transfer some data at beginning but then show above error.

**Comment by giftedunicorn** [comment]
It has no problem with uploading video to YouTube if connects to a leaf server. Used leaf 0.3.1 on client and server. 

leaf-server config
```
{
  "log": {
    "level": "trace"
  },
  "dns": {
      "servers": [
          "8.8.8.8"
      ]
  },
  "inbounds": [
    {
      "protocol":"trojan",
      "address":"0.0.0.0",
      "port": 443,
      "settings": {
          "password": "password"
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "direct"
    }
  ]
}

```

leaf-client.json
```
{
  "log": {
    "level": "trace"
  },
  "inbounds": [
    {
      "protocol": "socks",
      "address": "127.0.0.1",
      "port": 1080,
      "tag": "socks_in"
    }
  ],
  "outbounds": [
    {
      "protocol":"trojan",
      "settings":{
        "address":"1.2.3.4",
        "port":443,
        "password": "password"
      },
      "tag":"trojan_out"
    }
  ]
}
```

But it will have uploading issue with trojan-go server and trojan-gfw server. It will stuck at 29% when upload to YouTube. Or upload speed will drop to under 1.0 mbps when download can reach 300+ mbps on speedtest.com. 

trojan-go config
```
{
    "run_type": "server",
    "local_addr": "::",
    "local_port": 443,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "password": [
        "password"
    ],
    "ssl": {
        "cert": "/etc/trojan-go/a.example.net.pem",
        "key": "/etc/trojan-go/a.example.net.key",
        "sni": "a.example.net",
        "alpn": [
            "http/1.1"
        ],
        "session_ticket": true,
        "reuse_session": true,
        "fallback_addr": "127.0.0.1",
        "fallback_port": 80
    },
    "tcp": {
        "no_delay": true,
        "keep_alive": true,
        "prefer_ipv4": false
    },
    "mux": {
        "enabled": false,
        "concurrency": 8,
        "idle_timeout": 60
    },
    "websocket": {
        "enabled": false,
        "path": "",
        "host": "a.example.net"
    },
    "mysql": {
      "enabled": false,
      "server_addr": "localhost",
      "server_port": 3306,
      "database": "",
      "username": "",
      "password": "",
      "check_rate": 60
    }
}
```

**Comment by giftedunicorn** [comment]
Download is good. When upload 100M file to Google Drive, it will stop at some point and upload process will not move anymore. It shows the following errors from leaf client log.

Leaf client side log:
```
...
...
[2021-05-16 00:09:24][INFO] [socks] [tcp] [Proxy] [72ms] clients6.google.com:443
[2021-05-16 00:09:24][DEBUG] tcp uplink 127.0.0.1:53321 -> clients6.google.com:443 error: Connection reset by peer (os error 54) [Proxy]
[2021-05-16 00:09:24][TRACE] applied 4s downlink timeout to 127.0.0.1:53321 <- clients6.google.com:443
[2021-05-16 00:09:24][DEBUG] tcp downlink 127.0.0.1:53321 <- clients6.google.com:443 error: Broken pipe (os error 32) [Proxy]
[2021-05-16 00:09:24][DEBUG] tcp downlink 127.0.0.1:53321 <- clients6.google.com:443 error: Socket is not connected (os error 57) [Proxy]
...
...
```

Leaf: 0.3.1
Server: Trojan-Go (Tested with leaf server before, but the uploading works fine.)
Config: 
```
[General]
loglevel = trace
dns-server = 8.8.8.8
routing-domain-resolve = true
socks-interface = 127.0.0.1
socks-port = 1080

[Proxy]
Proxy = trojan, 1.2.3.4, 443, password=123123123, sni=a.example.com

[Rule]
EXTERNAL, site:cn, Direct
EXTERNAL, mmdb:cn, Direct
FINAL, Proxy
```

**Comment by giftedunicorn** [comment]
I tested with trojan-go + ws server. Then Leaf has no uploading issues.

**Comment by eycorsican** [comment]
Sounds like an issue related to tls, there are 2 tls backends available in leaf, have you tried both of them?

**Comment by FlyGGYe** [comment]
> I tested with trojan-go + ws server. Then Leaf has no uploading issues. 

Is this problem solved？

**Comment by giftedunicorn** [comment]
I'm going to use Trojan-go + ws for now. Have not tried different TLS yet.
