### ISSUE TITLE
leaf 0.3.0 release出来的包无法使用

### ISSUE THREAD

**Issue by gongxiaokai** [eycorsican/leaf#172]
leaf 0.3.0 release出来的包无法使用
libleaf.a 0.3.0无法使用
替换成之前的可以使用，麻烦大佬看一下？

**Comment by never-afk** [comment]
> leaf 0.3.0 release出来的包无法使用
> libleaf.a 0.3.0无法使用
> 替换成之前的可以使用，麻烦大佬看一下？

在IOS上发现了这个问题,是否已经解决?
