### ISSUE TITLE
[Question] can use leaf in commercial application?

### ISSUE THREAD

**Issue by mokhtarabadi** [eycorsican/leaf#184]
Hey @eycorsican 
I used your leaf in https://play.google.com/store/apps/details?id=org.hypervpn.android

Currently source code is closed, and this is  commercial app

Need I referred your github repo in my application about page?
Or can I use leaf in my app without referred it?

**Comment by eycorsican** [comment]
I'm pretty sure there is a LICENSE file.

**Comment by mokhtarabadi** [comment]
yes I know, I just wanted to ensure !!
