### ISSUE TITLE
[question] leaf 0.3.1 seems not working on linux

### ISSUE THREAD

**Issue by gjmzj** [eycorsican/leaf#187]
i'm not familiar with leaf, here is my testing:

os: ubuntu 1804
leaf version: 0.3.1 (9afcc27 - 2021-05-07 17:55:14 +0800)
conf:
```
[General]
loglevel = trace
dns-server = 114.114.114.114, 223.5.5.5
routing-domain-resolve = true
#always-real-ip = *
#dns-interface = 192.168.31.244

# Local SOCKS5 proxy with UDP Associate support
socks-interface = 127.0.0.1
socks-port = 1086

# TUN interface
#tun = tun2, 10.255.0.2, 255.255.255.0, 10.255.0.1, 1500

[Proxy]
Socks = socks, 47.110.x.x, 8118, interface=192.168.31.244
Direct = direct, interface=192.168.31.244
Reject = reject

[Rule]
IP-CIDR, 223.5.5.5/32, Direct
IP-CIDR, 114.114.114.114/32, Direct
IP-CIDR, 192.168.0.0/16, Direct
IP-CIDR, 10.0.0.0/8, Direct
IP-CIDR, 172.16.0.0/12, Direct
DOMAIN, www.baidu.com, Socks
DOMAIN-SUFFIX, sina.com, Socks
DOMAIN-KEYWORD, sina, Socks
PORT-RANGE, 3478-3478, Socks

FINAL, Reject
```

i ran with `./leaf -c /etc/leaf.conf`
```
start with options:
StartOptions {
    config: File(
        "/etc/leaf.conf",
    ),
    auto_reload: false,
    runtime_opt: MultiThreadAuto(
        131072,
    ),
}
[2021-05-27 10:53:37][DEBUG] default handler [Reject]
[2021-05-27 10:53:37][TRACE] add handler [Reject]
[2021-05-27 10:53:37][TRACE] add handler [Socks]
[2021-05-27 10:53:37][TRACE] add handler [Direct]
[2021-05-27 10:53:37][INFO] inbound listening tcp 127.0.0.1:1086
[2021-05-27 10:53:37][INFO] inbound listening udp 127.0.0.1:1086
```

and then i test with `curl www.baidu.com`, and no packet was captured on my remote socks server (47.110.x.x).

did i missed something, any suggestion will be appreciated

**Comment by mokhtarabadi** [comment]
add `tun = auto` in config
And add `GATEWAY_MODE=true` before running ./leaf
The above things transfer your whole Ubuntu traffic through leaf also make your Ubuntu as gateway
Mean in your phone you can change gateway to your Ubuntu ip, and enjoy 

This is easy way, hard way is create tuntap first and run leaf and then config network with ip command

**Comment by mokhtarabadi** [comment]
Currently in your config you opened port 1086 for socks5 incoming connections, but you didn't specify proxy for curl

**Comment by gjmzj** [comment]
thanks.
`tun = auto` got error: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 22, kind: InvalidInput, message: "Invalid argument" })', leaf/src/proxy/tun/inbound.rs:88:42

i fixed by following config
```
tun = tun2, 10.255.0.2, 255.255.255.0, 10.255.0.1, 1500
```

it worked as expected, thanks.

**Comment by mokhtarabadi** [comment]
@gjmzj 
I built leaf from the master branch and currently, my config is:
```
[General]
log-level = info
dns-server = 1.1.1.1

tun = auto

[Proxy]
Trojan = trojan, 1.2.3.4, 1234, password=password

[Rule]
FINAL, Trojan
```

and everything works, also need run leaf with root user

**Comment by gjmzj** [comment]
@mokhtarabadi thanks, i'll have a try

**Comment by gjmzj** [comment]
@mokhtarabadi when i built the master branch, got error:
```
The following warnings were emitted during compilation:

warning: cc: 错误：src/proxy/tun/netstack/lwip/core/init.c：没有那个文件或目录
warning: cc: 致命错误：没有输入文件
warning: 编译中断。

error: failed to run custom build command for `leaf v0.1.2 (/root/repo/leaf/leaf)`
```

**Comment by mokhtarabadi** [comment]
Did you use git to download leaf code?
If true run below commands in leaf directory
```bssh
git submodule init
git submodule update
```

**Comment by gjmzj** [comment]
> Did you use git to download leaf code?
> If true run below commands in leaf directory
> 
> ```
> git submodule init
> git submodule update
> ```

i successfully built the master branch, however the `tun = auto` didn't work all the same, but never mind, i am ok with configuring tun interfacde manually. could you explain the 'Gateway Mode' a little more

**Comment by gjmzj** [comment]
i supposed `leaf` behaves like `tun2socks`, and `tun2socks` needs to configure routing table to work

**Comment by nahddw** [comment]
I also have this problem on MacOS. 
It's working, but there's no network
What could be the reason?

log 
[tun] [tcp] [Fallback] [63ms] www.google.com:443

configuration info
[General]
loglevel = info
dns-server = 223.5.5.5, 114.114.114.114
routing-domain-resolve = true
tun = auto

[Proxy]
Direct = direct
Reject = reject
vmess-out = vmess, xxx, 443, username=xxxx

[Proxy Group]
Fallback = fallback, vmess-out, interval=600, timeout=5

[Rule]
EXTERNAL, site:cn, Direct
EXTERNAL, mmdb:cn, Direct
FINAL, Fallback

**Comment by mokhtarabadi** [comment]
> > Did you use git to download leaf code?
> > If true run the below commands in the leaf directory
> > ```
> > git submodule init
> > git submodule update
> > ```
> 
> I successfully built the master branch, however, the `tun = auto` didn't work all the same, but never mind, I am ok with configuring the tun interface manually. could you explain the 'Gateway Mode' a little more

gateway mode is useful in routers, for example, a cisco router, You can run leaf inside router with gateway mode, so all network  traffic will transfer through proxy

**Comment by mokhtarabadi** [comment]
> I supposed `leaf` `tun mode` behaves like `tun2socks`, and `tun2socks` needs to configure routing table to work

leaf didn't use tun2socks or other methods, leaf use [rust-tun](https://github.com/meh/rust-tun), and `tun=auto` will create tuntap and configure routing automatically

**Comment by 2856571872** [comment]
> I also have this problem on MacOS.
> It's working, but there's no network
> What could be the reason?
> 
> log
> [tun] [tcp] [Fallback] [63ms] [www.google.com:443](http://www.google.com:443)
> 
> configuration info
> [General]
> loglevel = info
> dns-server = 223.5.5.5, 114.114.114.114
> routing-domain-resolve = true
> tun = auto
> 
> [Proxy]
> Direct = direct
> Reject = reject
> vmess-out = vmess, xxx, 443, username=xxxx
> 
> [Proxy Group]
> Fallback = fallback, vmess-out, interval=600, timeout=5
> 
> [Rule]
> EXTERNAL, site:cn, Direct
> EXTERNAL, mmdb:cn, Direct
> FINAL, Fallback

Have you solved this problem?
