### ISSUE TITLE
Follow the steps in readme, but get errors bellow.

### ISSUE THREAD

**Issue by fuqiangleon** [eycorsican/leaf#188]
$ ls
build       config.json deps        examples    incremental leaf        leaf.d

$ ./leaf -h
Unrecognized argument: -h

**Comment by mokhtarabadi** [comment]
./leaf --help

**Comment by fuqiangleon** [comment]
@mokhtarabadi it works right now , thanks.

BTW,  does leaf support TLS  of v2ray?  I tested it several times but it failed.

**Comment by mokhtarabadi** [comment]
Yes support, create a chain first and then use tls and vmess for actors

**Comment by fuqiangleon** [comment]
@monnerHenster  Tks for your help.

I mean the properties:   security: "none" | "**tls**" ,  it does not work normally when I set it to "tls". 

For example:

![image](https://user-images.githubusercontent.com/1288399/120009548-a974a080-c00e-11eb-8a97-9717e5d9a6a7.png)

**Comment by mokhtarabadi** [comment]
How you config your leaf client?
Your configs seems v2ray not leaf
If can share leaf config so I can help you

> @monnerHenster Tks for your help.
> 
> I mean the properties: security: "none" | "**tls**" , it does not work normally when I set them to "tls" in client and server config file.
> 
> access log of v2ray server:
> rejected proxy/vmess/encoding: failed to read request header > tls: first record does not look like a TLS handshake
> 
> config of leaf:
> 
> ![image](https://user-images.githubusercontent.com/1288399/120009548-a974a080-c00e-11eb-8a97-9717e5d9a6a7.png)
> 
> config of v2ray server
> 
> ![image](https://user-images.githubusercontent.com/1288399/120010857-39ffb080-c010-11eb-9e14-edcb09aef103.png)

How you config your leaf client?
Your configs seems v2ray not leaf
If can share leaf config so I can help you

**Comment by fuqiangleon** [comment]
{
    "log": {
        "level": "debug"
    },
    "dns": {
        "servers": [
            "1.1.1.1",
            "8.8.8.8"
        ],
        "hosts": {
        }
    },
    "inbounds": [
        {
            "address": "127.0.0.1",
            "port": 1080,
            "protocol": "socks"
        }
    ],
    "outbounds": [
        {
            "protocol": "vmess",
            "settings": {
                "address": "server-name-here",
                "port": 20881,
                "uuid": "uuid-here"
            },
             "streamSettings": {
        "network": "tcp",
        "security": "none",
        "tlsSettings": {
          "allowInsecure": false,
          "serverName": ""
        }
      },
            "tag": "vmess"
        }
    ],
    "rules": [
        {
            "ip": [
                "192.168.88.0/24"
            ],
            "target": "vmess"
        }
    ]
}

**Comment by fuqiangleon** [comment]
@mokhtarabadi Hey bro,  you are right, I need to build a chain first and it works now. very appreciate your help. Have a good weekend.

 {
        "protocol": "chain",
        "settings": {
            "actors": [
                "vmess_tls",
                "vmess"
            ]
        },
        "tag": "vmess_out"
    },
    {
        "protocol": "tls",
        "settings": {
            "serverName": "onestar.cloud",
            "alpn": ["h2"]
        },
        "tag": "vmess_tls"
    },
