### ISSUE TITLE
iOS使用时无法联网，leaf v: 0.3.1

### ISSUE THREAD

**Issue by min554357332** [eycorsican/leaf#198]
调试	22:19:37.282290+0800	VPN	setting <private> in CFPrefsPlistSource<0x105c11f30> (Domain: group.com.xc.ios.initap, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No)
默认	22:19:37.296526+0800	VPN	\^[[90m[2021-06-30 22:19:37][\^[[90mTRACE\^[[0m\^[[90m] generate fake ip failed: unsupported query record type HTTPS\^[[0m
默认	22:19:37.296834+0800	VPN	\^[[37m[2021-06-30 22:19:37][\^[[37mDEBUG\^[[0m\^[[37m] added udp session 10.0.0.2:63484 -> 114.114.114.114:53 (1)\^[[0m
默认	22:19:37.296943+0800	VPN	\^[[90m[2021-06-30 22:19:37][\^[[90mTRACE\^[[0m\^[[90m] pick route failed: no matching rules\^[[0m
默认	22:19:37.297373+0800	VPN	\^[[37m[2021-06-30 22:19:37][\^[[37mDEBUG\^[[0m\^[[37m] allocate 198.18.0.8 for mesu.apple.com\^[[0m
默认	22:19:37.362543+0800	VPN	\^[[90m[2021-06-30 22:19:37][\^[[90mTRACE\^[[0m\^[[90m] netstack tcp new 10.0.0.2:60144\^[[0m
默认	22:19:37.362586+0800	VPN	\^[[90m[2021-06-30 22:19:37][\^[[90mTRACE\^[[0m\^[[90m] pick route failed: no matching rules\^[[0m
默认	22:19:37.362628+0800	VPN	\^[[33m[2021-06-30 22:19:37][\^[[33mWARN\^[[0m\^[[33m] can not find any handlers\^[[0m

config:
[General]
loglevel = trace
dns-server = 114.114.114.114
socks-interface = 127.0.0.1
socks-port = 1086
interface = 127.0.0.1
port = 1087
tun-fd = REPLACE-ME-WITH-THE-FD
routing-domain-resolve = false
[Proxy]
Direct = direct
Proxy = vmess, 107.150.97.143, 10086, username=c6effafd-6046-7a84-376e-b0429751c304
[Proxy Group]
[Rule]
FINAL, Proxy

leaf v: 0.3.1
ios sys v:14.2

连接后一直在shutdown->drop->new->pick route failed: no matching rules->can not find any handlers循环
leaf_test_config函数返回ERR_OK；
似乎是rule相关的错误。

**Comment by 2856571872** [comment]
> 调试 22:19:37.282290+0800 VPN setting in CFPrefsPlistSource<0x105c11f30> (Domain: group.com.xc.ios.initap, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No)
> 默认 22:19:37.296526+0800 VPN ^[[90m[2021-06-30 22:19:37][^[[90mTRACE^[[0m^[[90m] generate fake ip failed: unsupported query record type HTTPS^[[0m
> 默认 22:19:37.296834+0800 VPN ^[[37m[2021-06-30 22:19:37][^[[37mDEBUG^[[0m^[[37m] added udp session 10.0.0.2:63484 -> 114.114.114.114:53 (1)^[[0m
> 默认 22:19:37.296943+0800 VPN ^[[90m[2021-06-30 22:19:37][^[[90mTRACE^[[0m^[[90m] pick route failed: no matching rules^[[0m
> 默认 22:19:37.297373+0800 VPN ^[[37m[2021-06-30 22:19:37][^[[37mDEBUG^[[0m^[[37m] allocate 198.18.0.8 for mesu.apple.com^[[0m
> 默认 22:19:37.362543+0800 VPN ^[[90m[2021-06-30 22:19:37][^[[90mTRACE^[[0m^[[90m] netstack tcp new 10.0.0.2:60144^[[0m
> 默认 22:19:37.362586+0800 VPN ^[[90m[2021-06-30 22:19:37][^[[90mTRACE^[[0m^[[90m] pick route failed: no matching rules^[[0m
> 默认 22:19:37.362628+0800 VPN ^[[33m[2021-06-30 22:19:37][^[[33mWARN^[[0m^[[33m] can not find any handlers^[[0m
> 
> config:
> [General]
> loglevel = trace
> dns-server = 114.114.114.114
> socks-interface = 127.0.0.1
> socks-port = 1086
> interface = 127.0.0.1
> port = 1087
> tun-fd = REPLACE-ME-WITH-THE-FD
> routing-domain-resolve = false
> [Proxy]
> Direct = direct
> Proxy = vmess, 107.150.97.143, 10086, username=c6effafd-6046-7a84-376e-b0429751c304
> [Proxy Group]
> [Rule]
> FINAL, Proxy
> 
> leaf v: 0.3.1
> ios sys v:14.2
> 
> 连接后一直在shutdown->drop->new->pick route failed: no matching rules->can not find any handlers循环
> leaf_test_config函数返回ERR_OK；
> 似乎是rule相关的错误。

解决了没

**Comment by bikeboy7** [comment]
@min554357332 问题解决了吗
