### ISSUE TITLE
Vmess not work in conf.

### ISSUE THREAD

**Issue by johnmauser333** [eycorsican/leaf#201]
Hello, again vmess not working. SS and more work great, variable vmess not work. Only direct with vmess. SS and more great work. My config. 
`[General]
loglevel = info
dns-server = 1.1.1.1
tun = auto
always-real-ip = *

[Proxy]
Direct = direct 
Proxy = vmess, xxx, 443, username=xxx, ws=true, tls=true, ws-path=/sshocean

[Proxy Group]
[Rule]
FINAL, Proxy
[Host]
`

**Comment by alsojin0806** [comment]
描述清楚点，什么平台 tun = auto 不要乱用
