### ISSUE TITLE
流量统计不正确

### ISSUE THREAD

**Issue by bipo123** [eycorsican/leaf#208]
只能统计一个方向的字节数，上行或者下行。
看代码作者注释了 
 // let rw_shutdown = rw.shutdown();
打开发现 
报这个错误
cannot borrow `rw` as mutable more than once at a time
猜想是不是不能用 match future::select 这种方式来统计。

**Comment by eycorsican** [comment]
流量双向传输的逻辑需要重写是真的，但跟流量统计没什么关系。

**Comment by Sky891028** [comment]
请教下流量统计相关的代码在哪 
我通过哪个方法能拿到走代理的所有流量
