### ISSUE TITLE
Dont's support iOS 15

### ISSUE THREAD

**Issue by 2856571872** [eycorsican/leaf#221]

**Comment by HankHuangTianYu** [comment]
ios 15 FD different acquisition methods,you can try to get FD this way
    func getFD() -> Int32? {
        if #available(iOS 15, *) {
            var buf = [CChar](repeating: 0, count: Int(IFNAMSIZ))
            let utunPrefix = "utun".utf8CString.dropLast()
            return (0...1024).first { (_ fd: Int32) -> Bool in
                var len = socklen_t(buf.count)
                return getsockopt(fd, 2, 2, &buf, &len) == 0 && buf.starts(with: utunPrefix)
            }
        } else {
            return self.packetFlow.value(forKeyPath: "socket.fileDescriptor") as? Int32
        }
    }

**Comment by elsadeny** [comment]
@HankHuangTianYu Thank you,. it worked like a charm, but where did you get the information? I could like to learn more, i was stack for a week now

**Comment by HankHuangTianYu** [comment]
> @HankHuangTianYu Thank you,. it worked like a charm, but where did you get the information? I could like to learn more, i was stack for a week now

I've forgotten where this code came from, as I've known for a long time that ios15 can't get FD using the original method. I found this code while searching for information and verified its availability

**Comment by elsadeny** [comment]
How can I bypass some apps based on their bundle indentifier? on ios and macos?

**Comment by HankHuangTianYu** [comment]
> How can I bypass some apps based on their bundle indentifier? on ios and macos?

I don’t know, I also want to know, if you know the method later, please tell me

**Comment by bipo123** [comment]
https://blog.csdn.net/qq_26359763/article/details/118331747

**Comment by HankHuangTianYu** [comment]
> https://blog.csdn.net/qq_26359763/article/details/118331747

Is this blog,thanks

**Comment by HankHuangTianYu** [comment]
> How can I bypass some apps based on their bundle indentifier? on ios and macos?

Do you have WeChat, can we add WeChat to discuss this issue

**Comment by aliakhgar** [comment]
hi, is this still working? I'm testing it but no luck

**Comment by zxfmpy** [comment]
still have problems on mac system
