### ISSUE TITLE
大佬，请问有加入xtls支持的计划嘛

### ISSUE THREAD

**Issue by CoderTyn** [eycorsican/leaf#224]
iOS端从内测阶段一直在用，后面虽然加入了vless支持但并无xtls支持，请问有无计划加入xtls？

**Comment by eycorsican** [comment]
no

**Comment by xtls2** [comment]
> iOS端从内测阶段一直在用，后面虽然加入了vless支持但并无xtls支持，请问有无计划加入xtls？

支持vless了？咋弄？
