### ISSUE TITLE
最新代码编译出的ios静态库会出现PacketTunnel 15M内存崩溃问题

### ISSUE THREAD

**Issue by stoneport** [eycorsican/leaf#227]
使用0.3.1的正式版编译的ios静态库，没有碰到过上传大文件导致VPN崩溃的现象，用speedtest测试上传速度也没问题。不过0.3.1版本在iPhone上用起来感觉经常卡顿，特别是网页上域名特别多的页面。由于不知道怎么去调试，只能靠猜测感觉是UDP或者是DNS解析方面有某种问题。

这两天看到leaf有更新，就试着编译了一个新的ios库。测试下来刷页面非常流畅，没有卡顿的现象了。但是发现在电报等软件上传3张以上的图片都不行。用Speedtest测试，一到上传测试阶段，leaf就会出现15M内存崩溃的现象。

以前很多人讨论过ios NE 15M内存限制的问题，希望leaf在下一个正式版里能解决这个问题。

如果高手能指明一些调查方向，我也希望自己能为解决这个问题出点力量。

**Comment by imatrixme** [comment]
什么类型的线路？

**Comment by stoneport** [comment]
> 什么类型的线路？

服务器端是trojan-go, 但使用都是trojan标准的功能，没使用trojan-go的扩展配置。

相同的trojan配置在shadowrocket下使用完全没问题，上传大文件也非常流畅。

**Comment by eycorsican** [comment]
openssl

**Comment by stoneport** [comment]
> openssl

您是说编译时候对openssl的版本有什么特殊要求吗？

由于macos默认安装的是LibreSSL，我在编译前根据`brew info openssl`的提示结果，用命令将环境设置为使用openssl。版本为`OpenSSL 1.1.1l  24 Aug 2021`。不过编译出来的库，在ios下上传大文件时仍然会导致内存崩溃。

```bash
# 用以下命令切换了openssl。
cp ~/Downloads/cacert.pem /usr/local/etc/openssl@1.1/certs/
/usr/local/opt/openssl@1.1/bin/c_rehash

echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc
source ~/.zshrc

#For compilers to find openssl@1.1 you may need to set:
export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
```

我从appstore里下载了最新版的leaf，用相同的Trojan配置做了测试，发现不会出现崩内存的现象。估计还是我编译的有问题。
期待给些具体建议，或者发布一个您编译的版本。

**Comment by xtls2** [comment]
> > openssl
> 
> 您是说编译时候对openssl的版本有什么特殊要求吗？
> 
> 由于macos默认安装的是LibreSSL，我在编译前根据`brew info openssl`的提示结果，用命令将环境设置为使用openssl。版本为`OpenSSL 1.1.1l 24 Aug 2021`。不过编译出来的库，在ios下上传大文件时仍然会导致内存崩溃。
> 
> ```shell
> # 用以下命令切换了openssl。
> cp ~/Downloads/cacert.pem /usr/local/etc/openssl@1.1/certs/
> /usr/local/opt/openssl@1.1/bin/c_rehash
> 
> echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc
> source ~/.zshrc
> 
> #For compilers to find openssl@1.1 you may need to set:
> export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
> export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
> export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
> ```
> 
> 我从appstore里下载了最新版的leaf，用相同的Trojan配置做了测试，发现不会出现崩内存的现象。估计还是我编译的有问题。
> 期待给些具体建议，或者发布一个您编译的版本。

还有问题吗？解决了吗

**Comment by stoneport** [comment]
> 还有问题吗？解决了吗

没有解决问题，猜想应该是一些编译参数的问题。正在硬着头皮学习rust入门，希望多少能读懂一些这个很棒的项目。

作者大神已经把ileaf和aleaf项目删除了，不过好消息是应用商店的leaf都推出了新版本，以后可以直接使用作者亲自开发的App。

**Comment by codingiran** [comment]
将 bitcode 关闭
