### ISSUE TITLE
Cant archive IOS

### ISSUE THREAD

**Issue by monopolyApps** [eycorsican/leaf#245]
ld: Invalid value (Producer: 'LLVM13.0.0-rust-1.56.1-stable' Reader: 'LLVM APPLE_1_1300.0.29.3_0') for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by screenzen** [comment]
I'm having same issue Invalid value (Producer: 'LLVM13.0.0-rust-1.57.0-stable' Reader: 'LLVM APPLE_1_1300.0.29.3_0') for architecture arm64. Were you able to resolve?

**Comment by monopolyApps** [comment]
> I'm having same issue Invalid value (Producer: 'LLVM13.0.0-rust-1.57.0-stable' Reader: 'LLVM APPLE_1_1300.0.29.3_0') for architecture arm64. Were you able to resolve?

Project setting -> Enable Bitcode -> Change to NO
