### ISSUE TITLE
iOS PacketTunnel 进程崩溃

### ISSUE THREAD

**Issue by Arror** [eycorsican/leaf#266]
### Discussed in https://github.com/eycorsican/leaf/discussions/265

<div type='discussions-op-text'>

<sup>Originally posted by **Arror** April 17, 2022</sup>
iOS PacketTunnel 进程崩溃。

Branch：master

使用 make ios编译 libleaf.a

Cargo.toml：

[features]
default = [
    "leaf/config-json",
    "leaf/inbound-tun",
    "leaf/outbound-socks"
]

leaf-ffi/src/libs.rs：新增接口

```rust
#[no_mangle]
pub extern "C" fn leaf_run_with_config(rt_id: u16, config: *const c_char) -> i32 {
    if let Ok(_config) = unsafe { CStr::from_ptr(config).to_str() } {
        let opts = leaf::StartOptions {
            config: leaf::Config::Str(_config.to_string()),
            #[cfg(feature = "auto-reload")]
            auto_reload: false,
            runtime_opt: leaf::RuntimeOption::SingleThread,
        };
        if let Err(e) = leaf::start(rt_id, opts) {
            return to_errno(e);
        }
        ERR_OK
    } else {
        ERR_CONFIG
    }
}
```

接口调用：
```swift
leaf_run_with_config(987, config.cString(using: .utf8))
```

配置文件：
```json
{
    "log": {
        "level": "trace"
    },
    "inbounds": [
        {
            "protocol": "tun",
            "settings": {
                "fd": \(fd)
            },
            "tag": "tun"
        }
    ],
    "outbounds": [
        {
            "protocol": "socks",
            "settings": {
                "address": "127.0.0.1",
                "port": 8080
            },
            "tag": "clash"
        }
    ]
}
```

输出日志：

\^[[37m[2022-04-17 12:24:24][\^[[37mDEBUG\^[[0m\^[[37m] default handler [clash]\^[[0m
\^[[90m[2022-04-17 12:24:24][\^[[90mTRACE\^[[0m\^[[90m] added handler [clash]\^[[0m
\^[[90m[2022-04-17 12:24:24][\^[[90mTRACE\^[[0m\^[[90m] added runtime 987\^[[0m

崩溃堆栈：

  - 0 : "0   ???                                 0x0000000104fa89a0 0x0 + 4378495392"
  - 1 : "1   ???                                 0x0000000104fa8a2c 0x0 + 4378495532"
  - 2 : "2   PacketTunnel-iOS                    0x0000000102b55010 PacketTunnel-iOS + 5771280"
  - 3 : "3   libsystem_c.dylib                   0x00000001c6ca451c abort + 168"
  - 4 : "4   PacketTunnel-iOS                    0x0000000102976448 netif_add + 996"
  - 5 : "5   PacketTunnel-iOS                    0x0000000102974898 netif_init + 84"
  - 6 : "6   PacketTunnel-iOS                    0x00000001029747d8 lwip_init + 28"
  - 7 : "7   PacketTunnel-iOS                    0x0000000102b52658 _ZN3std4sync4once4Once10call_inner17hd5a75708fb5e7ae7E + 744"
  - 8 : "8   PacketTunnel-iOS                    0x00000001029f8ab4 _ZN97_$LT$core..future..from_generator..GenFuture$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$4poll17h5c6d3d814f45d00fE + 2112"
  - 9 : "9   PacketTunnel-iOS                    0x0000000102a06fbc _ZN97_$LT$core..future..from_generator..GenFuture$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$4poll17hac81694ea5332737E + 3016"
  - 10 : "10  PacketTunnel-iOS                    0x0000000102a7df78 _ZN103_$LT$futures_util..future..select_all..SelectAll$LT$Fut$GT$$u20$as$u20$core..future..future..Future$GT$4poll17h452499cb31f403eeE + 76"
  - 11 : "11  PacketTunnel-iOS                    0x0000000102a7a2c8 _ZN5tokio7runtime7Runtime8block_on17hcae03aeaceab0421E + 3260"
  - 12 : "12  PacketTunnel-iOS                    0x0000000102a78e3c _ZN4leaf5start17ha606316defa5e987E + 12236"
  - 13 : "13  PacketTunnel-iOS                    0x0000000102998c54 leaf_run_with_config + 172"
  - 14 : "14  PacketTunnel-iOS                    0x00000001025e0afc $s16PacketTunnel_iOS0aB8ProviderC05startB07optionsySDySSSo8NSObjectCGSg_tYaKFyyYbcfU2_ + 1540"
  - 15 : "15  PacketTunnel-iOS                    0x00000001025e0bec $sIegh_IeyBh_TR + 52"
  - 16 : "16  libdispatch.dylib                   0x00000001bb826e68 69DAC9C7-DDAF-318E-B068-BE596D142A2F + 7784"
  - 17 : "17  libdispatch.dylib                   0x00000001bb828a2c 69DAC9C7-DDAF-318E-B068-BE596D142A2F + 14892"
  - 18 : "18  libdispatch.dylib                   0x00000001bb82bb44 69DAC9C7-DDAF-318E-B068-BE596D142A2F + 27460"
  - 19 : "19  libdispatch.dylib                   0x00000001bb83a164 69DAC9C7-DDAF-318E-B068-BE596D142A2F + 86372"
  - 20 : "20  libdispatch.dylib                   0x00000001bb83a96c 69DAC9C7-DDAF-318E-B068-BE596D142A2F + 88428"
  - 21 : "21  libsystem_pthread.dylib             0x000000022cb46080 _pthread_wqthread + 228"
  - 22 : "22  libsystem_pthread.dylib             0x000000022cb45e5c start_wqthread + 8"</div>

**Comment by WangLiquan** [comment]
@daemonomead 兄弟这个你后来找到解决办法了吗
