### ISSUE TITLE
JNI or JNA

### ISSUE THREAD

**Issue by tuncatunc** [eycorsican/leaf#286]
I want to put the leaf into an Android app. Should I interface it using JNI or JNA?

**Comment by syf-work** [comment]
建议 JNI

**Comment by tuncatunc** [comment]
Update the crate-type to "cdylib" according to
[https://docs.rs/jni/latest/jni/#the-rust-side](https://docs.rs/jni/latest/jni/#the-rust-side)
`cargo build -p leaf-ffi` genarates following error.

How can I build the leaf-ffi?

Thanks

<details>
<summary>cargo build -p leaf-ffi</summary>
PS C:\Users\xxxx\Local\Temp\git\leaf> cargo build -p leaf-ffi
warning: unused import: `std::ffi::CString`
 --> leaf\src\proxy\mod.rs:1:5
  |
1 | use std::ffi::CString;
  |     ^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused variable: `iface`
   --> leaf\src\proxy\mod.rs:203:37
    |
203 |             OutboundBind::Interface(iface) => {
    |                                     ^^^^^ help: if this is intentional, prefix it with an underscore: `_iface`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: variable does not need to be mutable
   --> leaf\src\app\inbound\manager.rs:236:13
    |
236 |         let mut tun_auto = false;
    |             ----^^^^^^^^
    |             |
    |             help: remove this `mut`
    |
    = note: `#[warn(unused_mut)]` on by default

warning: `leaf` (lib) generated 3 warnings
   Compiling leaf-ffi v0.1.0 (C:\Users\hurjet\AppData\Local\Temp\git\leaf\leaf-ffi)
error[E0433]: failed to resolve: use of undeclared crate or module `leaf`
  --> leaf-ffi\src/lib.rs:22:16
   |
22 | fn to_errno(e: leaf::Error) -> i32 {
   |                ^^^^ use of undeclared crate or module `leaf`

error[E0433]: failed to resolve: use of undeclared crate or module `leaf`
  --> leaf-ffi\src/lib.rs:24:9
   |
24 |         leaf::Error::Config(..) => ERR_CONFIG,
   |         ^^^^ use of undeclared crate or module `leaf`

error[E0433]: failed to resolve: use of undeclared crate or module `leaf`
  --> leaf-ffi\src/lib.rs:25:9
   |
25 |         leaf::Error::NoConfigFile => ERR_NO_CONFIG_FILE,
   |         ^^^^ use of undeclared crate or module `leaf`

error[E0433]: failed to resolve: use of undeclared crate or module `leaf`
  --> leaf-ffi\src/lib.rs:26:9
   |
26 |         leaf::Error::Io(..) => ERR_IO,
   |         ^^^^ use of undeclared crate or module `leaf`

error[E0433]: failed to resolve: use of undeclared crate or module `leaf`
  --> leaf-ffi\src/lib.rs:29:9
   |
29 |         leaf::Error::AsyncChannelSend(..) => ERR_ASYNC_CHANNEL_SEND,
   |         ^^^^ use of undeclared crate or module `leaf`

error[E0433]: failed to resolve: use of undeclared crate or module `leaf`
  --> leaf-ffi\src/lib.rs:30:9
   |
30 |         leaf::Error::SyncChannelRecv(..) => ERR_SYNC_CHANNEL_RECV,
   |         ^^^^ use of undeclared crate or module `leaf`

error[E0433]: failed to resolve: use of undeclared crate or module `leaf`
  --> leaf-ffi\src/lib.rs:31:9
   |
31 |         leaf::Error::RuntimeManager => ERR_RUNTIME_MANAGER,
   |         ^^^^ use of undeclared crate or module `leaf`

error[E0433]: failed to resolve: use of undeclared crate or module `leaf`
  --> leaf-ffi\src/lib.rs:65:25
   |
65 |         if let Err(e) = leaf::util::run_with_options(
   |                         ^^^^ use of undeclared crate or module `leaf`

error[E0433]: failed to resolve: use of undeclared crate or module `leaf`
  --> leaf-ffi\src/lib.rs:94:20
   |
94 |         let opts = leaf::StartOptions {
   |                    ^^^^ use of undeclared crate or module `leaf`

error[E0433]: failed to resolve: use of undeclared crate or module `leaf`
  --> leaf-ffi\src/lib.rs:95:21
   |
95 |             config: leaf::Config::File(config_path.to_string()),
   |                     ^^^^ use of undeclared crate or module `leaf`

error[E0433]: failed to resolve: use of undeclared crate or module `leaf`
  --> leaf-ffi\src/lib.rs:98:26
   |
98 |             runtime_opt: leaf::RuntimeOption::SingleThread,
   |                          ^^^^ use of undeclared crate or module `leaf`

error[E0433]: failed to resolve: use of undeclared crate or module `leaf`
   --> leaf-ffi\src/lib.rs:100:25
    |
100 |         if let Err(e) = leaf::start(rt_id, opts) {
    |                         ^^^^ use of undeclared crate or module `leaf`

error[E0433]: failed to resolve: use of undeclared crate or module `leaf`
   --> leaf-ffi\src/lib.rs:112:20
    |
112 |         let opts = leaf::StartOptions {
    |                    ^^^^ use of undeclared crate or module `leaf`

error[E0433]: failed to resolve: use of undeclared crate or module `leaf`
   --> leaf-ffi\src/lib.rs:113:21
    |
113 |             config: leaf::Config::Str(config.to_string()),
    |                     ^^^^ use of undeclared crate or module `leaf`

error[E0433]: failed to resolve: use of undeclared crate or module `leaf`
   --> leaf-ffi\src/lib.rs:116:26
    |
116 |             runtime_opt: leaf::RuntimeOption::SingleThread,
    |                          ^^^^ use of undeclared crate or module `leaf`

error[E0433]: failed to resolve: use of undeclared crate or module `leaf`
   --> leaf-ffi\src/lib.rs:118:25
    |
118 |         if let Err(e) = leaf::start(rt_id, opts) {
    |                         ^^^^ use of undeclared crate or module `leaf`

error[E0433]: failed to resolve: use of undeclared crate or module `leaf`
   --> leaf-ffi\src/lib.rs:134:21
    |
134 |     if let Err(e) = leaf::reload(rt_id) {
    |                     ^^^^ use of undeclared crate or module `leaf`

error[E0433]: failed to resolve: use of undeclared crate or module `leaf`
   --> leaf-ffi\src/lib.rs:147:5
    |
147 |     leaf::shutdown(rt_id)
    |     ^^^^ use of undeclared crate or module `leaf`

error[E0433]: failed to resolve: use of undeclared crate or module `leaf`
   --> leaf-ffi\src/lib.rs:158:25
    |
158 |         if let Err(e) = leaf::test_config(&config_path) {
    |                         ^^^^ use of undeclared crate or module `leaf`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `leaf-ffi` due to 19 previous errors</details>

**Comment by tuncatunc** [comment]
I'll answer my own question,
only changed the `leaf-ffi` cargo.toml `
```toml
[lib]
name = "leafffi"
path = "src/lib.rs"
crate-type = ["cdylib"]
```
`cargo build -p leaf-ffi` works and generated `leafffi.dll` i copied it under the java and successfully used.

**Comment by HankLi0130** [comment]
Hi @tuncatunc, may I know how to compile `leaf-ffi` as a library and use it in Android? I wrote a JNI layer to call `leaf` methods and didn't use `leaf-ffi`. Just want to know other solutions. Thank you.

**Comment by tuncatunc** [comment]
Hi @HankLi0130 

https://docs.rs/jni/latest/jni/

Would be great start

**Comment by HankLi0130** [comment]
@tuncatunc thank you for replying. I'm using the same tools as you do, but I call the functions in `leaf` package instead of `leaf-ffi` package. Is there any advantage to use `leaf-ffi` in JNI layer ?

**Comment by HankLi0130** [comment]
I think JNI is the same layer as the ffi, doesn't it ?

**Comment by tuncatunc** [comment]
Hey Hank,
Yes they're the same thing.
