### ISSUE TITLE
夜神模拟器（安卓7.1.2版本）socks5代理连接失败

### ISSUE THREAD

**Issue by ChenDing2018** [eycorsican/leaf#290]
运行环境：aleaf 运行在夜神模拟器 android7上（android9正常）

报错日志
![image](https://user-images.githubusercontent.com/45548541/174514208-47cb61d2-fb11-4684-84db-555984a9246a.png)

**Comment by ChenDing2018** [comment]
连接服务器内网ip，代理正常，连接服务器公网ip,代理失败，报上面错误信息

**Comment by 52yaoer** [comment]
你好。。你的配置文件怎么写的啊。。我socks5服务端部署好了，，现在不晓得配置文件咋写。。

**Comment by chentao7v** [comment]
@52yaoer 你好，你的配置怎么写的啊 socks5
