### ISSUE TITLE
Package & License Request

### ISSUE THREAD

**Issue by DuckSoft** [eycorsican/leaf#3]
This is @DuckSoft from @archlinuxcn. I write on behalf of myself.
I would like to package `leaf` into [AUR](https://aur.archlinux.org/) and @archlinuxcn.

I am writing to officially request your permission for everyone:
1. To redistribute release assets from this repo as-is.
2. To package aforementioned binaries freely into distro-specific formats, for example, Debian, Arch Linux, Chocolatey, Scoop etc. In this case, your binary might get processed by some unopinioned tools, for example, stripping out and splitting debug symbols to meet the packaging standards.

What's more, it would be nice if we have a LICENSE file in the repo, since many package managers and software repositories require the LICENSE to be clearly specified. I would recommend a https://choosealicense.com/licenses/apache-2.0/ here.

Thank you!

**Comment by eycorsican** [comment]
It's now licensed under `Apache License 2.0`.
