### ISSUE TITLE
How to use this library to make an iOS app

### ISSUE THREAD

**Issue by aravindhkumar23** [eycorsican/leaf#303]
I am planning to use this library to build an iOS app to implement a VPN tunnel using WebSockets, but I don't find any documentation to consume it in the iOS project.
I have seen a similar issue raised [here ](https://github.com/eycorsican/leaf/issues/7), and provided with a demo [app source ](https://github.com/eycorsican/ileaf) but the link is not accessible.

can I get a sample source/how to integrate it into the project documentation?

**Comment by eycorsican** [comment]
https://github.com/eycorsican/leaf/issues/297#issuecomment-1220258917
