### ISSUE TITLE
TUN has no effect

### ISSUE THREAD

**Issue by nimagp** [eycorsican/leaf#307]
I'm trying to route the entire traffic trough a socks proxy running local (shadowsocks-rust, in fact). but running leaf with this config doesn't have any effect:
![](https://cdn.discordapp.com/attachments/864781217835384833/1027238831075897375/unknown.png)
If I use `sudo ip route add default via 10.10.0.1 dev utun8 metric 1` all requests result in "Connection closed", but looks like leaf finally catches something:
![image](https://user-images.githubusercontent.com/71447191/194109291-9ba8f719-5868-4b31-8f26-94c396fb4950.png)

`sudo ip route add 0.0.0.0/0 by 10.10.0.1 dev utun8` doesn't have any effect either.

Hope these help:
![](https://cdn.discordapp.com/attachments/864781217835384833/1027238830249619587/unknown.png)
![](https://cdn.discordapp.com/attachments/864781217835384833/1027238830639697960/unknown.png)
![](https://cdn.discordapp.com/attachments/864781217835384833/1027238829880528896/unknown.png)

Thanks.

**Comment by syf-work** [comment]
i think you should paste the outbound config, so the problem can be resolved.

**Comment by nimagp** [comment]
I've erased it. But nothing special, shadowsocks client running on my own device. Routing traffic to shadowsocks server through default gateway doesn't have any effect either.

**Comment by syf-work** [comment]
i use macos, it's ok, the stream flow like below:

local packet stream -> tun address -> tun gateway -> default gateway -> your outbound server
