### ISSUE TITLE
能添加VmessAEAD支持吗

### ISSUE THREAD

**Issue by Rosario9527** [eycorsican/leaf#309]
alterId为0时，v2ray默认开启了VmessAEAD, leaf也没有alterId的配置， 大佬能支持下VmessAEAD吗， 或者能配置alterId。

Best Regards!

**Comment by chenkai2** [comment]
+1
配置alterId，
加密方式（security）支持auto：自动选择（运行框架为 AMD64、ARM64 或 s390x 时为 aes-128-gcm 加密方式，其他情况则为 Chacha20-Poly1305 加密方式）

**Comment by sbh96** [comment]
Yes same issue

**Comment by MakeMoney-Hash** [comment]
花了一星期的功夫，我解决了它

**Comment by zfuke164345** [comment]
me too

**Comment by MakeMoney-Hash** [comment]
> me too

作者没有计划支持。大佬还是自己写一个吧

**Comment by Web3123** [comment]
https://github.com/Web3123/v2ray 这是项目地址
