### ISSUE TITLE
UDP over socks outbound

### ISSUE THREAD

**Issue by mukswilly** [eycorsican/leaf#312]
Are there any plans to support UDP over the socks outbound? UDP traffic seems not to be proxied to a socks outbound even if the socks proxy has support for UDP ASSOCIATE. Thanks.

**Comment by syf-work** [comment]
i think the vmess and trojan protocol support UDP over tcp, you can follow that code.

**Comment by mukswilly** [comment]
> i think the vmess and trojan protocol support UDP over tcp, you can follow that code.

Thanks for the advice. I'm not conversant with Rust. I guess I will just have to gamble around copy-pasting and editing.
