### ISSUE TITLE
support VMess AEAD / alterid

### ISSUE THREAD

**Issue by sbh96** [eycorsican/leaf#322]
please support vmess AEAD
without AEAD v2ray users cannot use leaf
please dont close issue let team to solve this issue
thanks

**Comment by sbh96** [comment]
nobody wants to fix this issue?
in Iran, we have a problem connecting to internet only v2ray is working thanks of china and Iran government! because china sales filtering technology to Iran government.
please support vmess ahead then we can implement it in the application to access free internet in Iran 
@vkill @EkkoG @bdbai  @perqin  @eycorsican

**Comment by KouYiGuo** [comment]
I suggest you to research [orbot-apple](https://github.com/guardianproject/orbot-apple). The guardian project use two level implementation. You can use leaf as tun2socks service and use socks as v2ray-core inbound. Then you'll get an app which supports full v2ray features.
If you just want a free v2ray app but not to develop it, you can use [Wings V Client](https://apps.apple.com/us/app/wings-v-client/id1659637036).

**Comment by MakeMoney-Hash** [comment]
i also want it

**Comment by MakeMoney-Hash** [comment]
I've solved it and I'm very happy

**Comment by bdbai** [comment]
@MakeMoney-Hash GitHub is a place for open source software. Please share your code instead.

**Comment by Web3123** [comment]
https://github.com/Web3123/v2ray 这是项目地址
