### ISSUE TITLE
0.6.0和最新的git fa017bb 版本，windows下，inbound的http代理均无法正常使用，而socks代理可以正常使用，是否存在问题？

### ISSUE THREAD

**Issue by nivrrex** [eycorsican/leaf#329]
如题所述，使用了两种配置模板，socks代理可以正常使用，log日志也出现了端口绑定的提示
但是http代理无任何端口绑定的log日志，也无法正常代理使用，
windows10系统
是否存在bug？

**Comment by zy9306** [comment]
把这个取消注释重新编译就能用了 https://github.com/eycorsican/leaf/blob/master/leaf/Cargo.toml#L50
