### ISSUE TITLE
连接trojan-go的服务器出现BadCertificate

### ISSUE THREAD

**Issue by Yewenyu** [eycorsican/leaf#333]
可以关闭tls的验证吗

**Comment by llwijvbw123** [comment]
能添加自己的ca证书也行呀

**Comment by MakeMoney-Hash** [comment]
可以关闭tls,这个问题我解决了

**Comment by Yewenyu** [comment]
> 可以关闭tls,这个问题我解决了

你好，请问怎么解决的

**Comment by MakeMoney-Hash** [comment]
> 

你可以看llwijvbw123他fork的代码,代码改动里面解决了

**Comment by MakeMoney-Hash** [comment]
> > 可以关闭tls,这个问题我解决了
> 
> 你好，请问怎么解决的

你可以留下你的tg

**Comment by MakeMoney-Hash** [comment]
> > 可以关闭tls,这个问题我解决了
> 
> 你好，请问怎么解决的

解决了吧？没想到22年的问题 你还一直在关注

**Comment by rendaoer** [comment]
> > > > 可以关闭tls,这个问题我解决了
> > > 
> > > 
> > > 你好，请问怎么解决的
> > 
> > 
> > 解决了吧？没想到22年的问题 你还一直在关注
> 
> 嗯，看到了，感谢感谢，对rust不熟，所以不知道怎么解决，只能做伸手党了

请问你们解决问题的办法去哪了，可以说说是怎么解决的吗

**Comment by MakeMoney-Hash** [comment]
> > > > > 可以关闭tls,这个问题我解决了
> 
> > > > 
> 
> > > > 
> 
> > > > 你好，请问怎么解决的
> 
> > > 
> 
> > > 
> 
> > > 解决了吧？没想到22年的问题 你还一直在关注
> 
> > 
> 
> > 嗯，看到了，感谢感谢，对rust不熟，所以不知道怎么解决，只能做伸手党了
> 
> 
> 
> 请问你们解决问题的办法去哪了，可以说说是怎么解决的吗
 看最新代码吧

**Comment by rendaoer** [comment]
> > > > > 可以关闭tls,这个问题我解决了
> 
> > > >
> 
> > > >
> 
> > > > 你好，请问怎么解决的
> 
> > >
> 
> > >
> 
> > > 解决了吧？没想到22年的问题 你还一直在关注
> 
> > 
> 
> > 嗯，看到了，感谢感谢，对rust不熟，所以不知道怎么解决，只能做伸手党了
> 
> 请问你们解决问题的办法去哪了，可以说说是怎么解决的吗 看最新代码吧

怎么关闭啊，可以教我一下吗

**Comment by MakeMoney-Hash** [comment]
> > > > > > 可以关闭tls,这个问题我解决了
> 
> > 
> 
> > > > >
> 
> > 
> 
> > > > >
> 
> > 
> 
> > > > > 你好，请问怎么解决的
> 
> > 
> 
> > > >
> 
> > 
> 
> > > >
> 
> > 
> 
> > > > 解决了吧？没想到22年的问题 你还一直在关注
> 
> > 
> 
> > > 
> 
> > 
> 
> > > 嗯，看到了，感谢感谢，对rust不熟，所以不知道怎么解决，只能做伸手党了
> 
> > 
> 
> > 请问你们解决问题的办法去哪了，可以说说是怎么解决的吗 看最新代码吧
> 
> 
> 
> 怎么关闭啊，可以教我一下吗


留下你的联系方式

**Comment by rendaoer** [comment]
> > > > > > > 可以关闭tls,这个问题我解决了
> > 
> > 
> > > 
> > 
> > 
> > > > > >
> > 
> > 
> > > 
> > 
> > 
> > > > > >
> > 
> > 
> > > 
> > 
> > 
> > > > > > 你好，请问怎么解决的
> > 
> > 
> > > 
> > 
> > 
> > > > >
> > 
> > 
> > > 
> > 
> > 
> > > > >
> > 
> > 
> > > 
> > 
> > 
> > > > > 解决了吧？没想到22年的问题 你还一直在关注
> > 
> > 
> > > 
> > 
> > 
> > > >
> > 
> > 
> > > 
> > 
> > 
> > > > 嗯，看到了，感谢感谢，对rust不熟，所以不知道怎么解决，只能做伸手党了
> > 
> > 
> > > 
> > 
> > 
> > > 请问你们解决问题的办法去哪了，可以说说是怎么解决的吗 看最新代码吧
> > 
> > 
> > 怎么关闭啊，可以教我一下吗
> 
> 留下你的联系方式

qq:2604808757

**Comment by 52yaoer** [comment]
> > > > > > > 可以关闭tls,这个问题我解决了
> > 
> > 
> > > 
> > 
> > 
> > > > > >
> > 
> > 
> > > 
> > 
> > 
> > > > > >
> > 
> > 
> > > 
> > 
> > 
> > > > > > 你好，请问怎么解决的
> > 
> > 
> > > 
> > 
> > 
> > > > >
> > 
> > 
> > > 
> > 
> > 
> > > > >
> > 
> > 
> > > 
> > 
> > 
> > > > > 解决了吧？没想到22年的问题 你还一直在关注
> > 
> > 
> > > 
> > 
> > 
> > > >
> > 
> > 
> > > 
> > 
> > 
> > > > 嗯，看到了，感谢感谢，对rust不熟，所以不知道怎么解决，只能做伸手党了
> > 
> > 
> > > 
> > 
> > 
> > > 请问你们解决问题的办法去哪了，可以说说是怎么解决的吗 看最新代码吧
> > 
> > 
> > 怎么关闭啊，可以教我一下吗
> 
> 留下你的联系方式

我也想咨询下如何关闭tls，

qq： 176142998

**Comment by MakeMoney-Hash** [comment]
> > > > > > > > 可以关闭tls,这个问题我解决了
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > > > > 你好，请问怎么解决的
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > > > 解决了吧？没想到22年的问题 你还一直在关注
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > > 嗯，看到了，感谢感谢，对rust不熟，所以不知道怎么解决，只能做伸手党了
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 请问你们解决问题的办法去哪了，可以说说是怎么解决的吗 看最新代码吧
> 
> > > 
> 
> > > 
> 
> > > 怎么关闭啊，可以教我一下吗
> 
> > 
> 
> > 留下你的联系方式
> 
> 
> 
> 我也想咨询下如何关闭tls，
> 
> 
> 
> qq： 176142998


TG吧

**Comment by liqianjie** [comment]
> > > > > > > > > 可以关闭tls,这个问题我解决了
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > 你好，请问怎么解决的
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > 解决了吧？没想到22年的问题 你还一直在关注
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 嗯，看到了，感谢感谢，对rust不熟，所以不知道怎么解决，只能做伸手党了
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 请问你们解决问题的办法去哪了，可以说说是怎么解决的吗 看最新代码吧
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 怎么关闭啊，可以教我一下吗
> > 
> > 
> > > 
> > 
> > 
> > > 留下你的联系方式
> > 
> > 
> > 我也想咨询下如何关闭tls，
> > qq： 176142998
> 
> TG吧

我的TG: eviliori
