### ISSUE TITLE
多线程环境下：lwip mem_free double free

### ISSUE THREAD

**Issue by ChenDing2018** [eycorsican/leaf#342]
mac os下：
conf:
[General]
loglevel = trace
dns-server = 223.5.5.5
tun=auto
[Proxy]
Direct = direct
[Rule]
FINAL, Direct

运行一会就会报错：
Assertion "mem_free: illegal memory: non-linked: double free" failed at line 661 in src/lwip/core/mem.c

**Comment by ChenDing2018** [comment]
多线程环境执行

**Comment by eycorsican** [comment]
Assumed fixed in 0.7.0
