### ISSUE TITLE
请问iOS conf如何配置Cloudflare

### ISSUE THREAD

**Issue by 1725595559** [eycorsican/leaf#348]
[Proxy]
Direct = direct
Proxy=vmess,example.com,443,username=0eb5486e-e1b5-49c5-aa75-d15e54dfac9d, ws=true, tls=true, ws-path=/v2
我目前是这样配置，但是带Cloudflare节点连接不能访问，但是用第三方的app添加该节点能正常使用

**Comment by zhouyuzhouyu** [comment]
@1725595559 你好，我也碰到了同样的问题，请问是如何解决的？
