### ISSUE TITLE
Reversed IP using tun mode on MIPS Architecture in 0.7.0

### ISSUE THREAD

**Issue by Keith-amateur** [eycorsican/leaf#354]
## reversed 0.7.0
![2023-03-08-005145_1299x331_scrot](https://user-images.githubusercontent.com/83109029/223494061-d903adf6-9c65-49c8-b99e-da9551fc18c5.png)
## normal 0.6.0(works fine)
![2023-03-08-011644_1229x320_scrot](https://user-images.githubusercontent.com/83109029/223498452-b9d69acb-48e0-4c6e-bdb5-56858ce507fc.png)
### config file
```
[General]
loglevel = debug
always-real-ip = *
tun = auto

[Proxy]
Direct = direct

[Rule]
FINAL, Direct
```
However TUN inbound works on mipel in 0.7.0. 
I am not an expert in programming. I guess IP addresses are all parsed in little endian.Hence, IP will be reversed on big-endian architecture.

**Comment by eycorsican** [comment]
Made an attempt to fix the issue: https://github.com/eycorsican/netstack-lwip/commit/dbcc404206e1e7bf5abd7984f64a7a5fcd4c1457

**Comment by Keith-amateur** [comment]
Thank you!
