### ISSUE TITLE
[Proposal] Shadowsocks simple-obfs outbound

### ISSUE THREAD

**Issue by bdbai** [eycorsican/leaf#362]
I would like to propose simple-obfs outbound feature for Shadowsocks proxy. Any ideas or suggestions are welcome.

## Feature Breakdown

- Add a default, optional feature `outbound-obfs`
- Implement `OutboundStreamHandler` for HTTP obfs handler
- Implement `OutboundStreamHandler` for TLS obfs handler
- Add conf attributes for obfs type and params to Shadowsocks proxy
    - `obfs`: `http`/`tls`
    - `obfs-host`: Hostname for obfs headers
- Add JSON entry for obfs outbound
    - `protocol`: `obfs`
    - `settings.mode`: `http`/`tls`
    - `settings.host`: Hostname for obfs headers

## Proposed Implementation

Refer to [simple-obfs](https://github.com/shadowsocks/simple-obfs) and [Clash](https://github.com/Dreamacro/clash/tree/d808576f98019529f098476df979c7bcf2822c84/transport/simple-obfs).

**Comment by bdbai** [comment]
@eycorsican do you think it is a good-to-have or have any other opinions? I can help with the implementation if you are okay with it.

**Comment by eycorsican** [comment]
I'm open to this kind of outbound being merged in to leaf as long as they are made as optional features.
