### ISSUE TITLE
iOS: how to deal with protect?

### ISSUE THREAD

**Issue by gregoiregentil** [eycorsican/leaf#377]
This issue/question is the Android corresponding issue of [376](https://github.com/eycorsican/leaf/issues/376) for iOS. I don't think that it's really a leaf issue, but more an iOS question. Feel free to close it if you want to.

I have integrated leaf in an iOS app based on the ileaf example. My 127.0.0.1 socket server lives in the app, and the VPN extension based on NEPacketTunnelProvider is leveraging leaf.

How do I exclude the traffic of my socket in my app from the VPN extension/leaf?

- is there an iOS equivalent of Android addDisallowedApplication? I have searched SO and I couldn't find a clear answer.
- should I use Direct in leaf with the right set of rules?
- is the best strategy to put my socket server in the VPN extension?

**Comment by eycorsican** [comment]
You don't need to protect the sockets on iOS, the outgoing traffic in the extension are excluded from the VPN tunnel.
