### ISSUE TITLE
同一个局域网规则配置无效，需要直连，查看日志走的代理

### ISSUE THREAD

**Issue by shaohuihu** [eycorsican/leaf#382]
配置文件如下:
[General]
loglevel = trace
dns-server = 223.5.5.5, 114.114.114.114
tun-fd = REPLACE-ME-WITH-THE-FD
routing-domain-resolve = true

[Proxy]
Direct = direct
Proxy = vmess, 89.44.9.159, 3188, username=c4f4c71d-52b2-44b8-a023-babf552ac58c

[Rule]
EXTERNAL, site:cn, Direct
EXTERNAL, mmdb:cn, Direct
GEOIP, private, Direct
EXTERNAL, mmdb:private, Direct
FINAL, Proxy

其中GEOIP, private, Direct 和 EXTERNAL, mmdb:private, Direct 没有生效
电脑和手机在同一局域网，电脑上开启一个http服务器，手机上去访问走的代理，断开vpn 可以正常访问。请问规则如何配置？

**Comment by eycorsican** [comment]
mmdb 只支持 country code，private 不是 country code
