### ISSUE TITLE
xcframework的使用问题

### ISSUE THREAD

**Issue by rendaoer** [eycorsican/leaf#383]
从0.8.2版本下载的xcframework，在Mac app下是可以正常import，但是iOS app就导入不了
<img width="803" alt="image" src="https://user-images.githubusercontent.com/46780118/236391554-002a103a-cd7e-4fbc-9386-932bbc476143.png">
<img width="376" alt="image" src="https://user-images.githubusercontent.com/46780118/236391616-6cb002f0-3047-4ede-b542-f64b113d1439.png">
<img width="400" alt="image" src="https://user-images.githubusercontent.com/46780118/236391681-afe25eff-1d7e-4103-b698-01f9d30e52a4.png">

有人知道怎么解决吗？

**Comment by rendaoer** [comment]
好像还会报错说不支持iOS模拟器架构
<img width="237" alt="image" src="https://user-images.githubusercontent.com/46780118/236400220-93177784-243e-4c83-8625-15ca1020df38.png">

**Comment by eycorsican** [comment]
只能要选 do not embed？

**Comment by rendaoer** [comment]
> 只能要选 do not embed？
我没听懂，你是说改成
<img width="554" alt="image" src="https://user-images.githubusercontent.com/46780118/236667002-cf8fb149-7116-4ea0-a81f-8df7b27f1f61.png">
这样吗？但是还是一样import leaf 不了

**Comment by eycorsican** [comment]
ios vpn 至少有 host app 和 extension 两个 target，是不是没导入到正确的 target 中？

**Comment by rendaoer** [comment]
我是这个样子的
<img width="948" alt="image" src="https://user-images.githubusercontent.com/46780118/236667987-272c853a-a8bc-47bb-8c58-620255f80d05.png">
Mac 这边的是可以正常import

**Comment by rendaoer** [comment]
我尝试自己编译一份之后，竟然可以了，感谢作者 @eycorsican

**Comment by catter-dev** [comment]
How did you compiled and generated **.xcframework** files?  As i have compiled for ios and got to use **libleaf.a** file and then added this into my target.
<img width="706" alt="image" src="https://github.com/eycorsican/leaf/assets/122444484/7de143f4-fefa-4212-90b4-f85673319c37">
