### ISSUE TITLE
leaf-android-libs里面的so怎么用啊？

### ISSUE THREAD

**Issue by 52yaoer** [eycorsican/leaf#395]
有高手指导下么？leaf-android-libs里面的so怎么用?

**Comment by 52yaoer** [comment]
目前已经用上了，，这个问题关闭了，

**Comment by Shameless521** [comment]
leaf-android-libs 这个怎么使用呀

**Comment by mhlywxl** [comment]
> leaf-android-libs 这个怎么使用呀

qq:3256509052

**Comment by 52yaoer** [comment]
android里面编译ndk去调用的。
