### ISSUE TITLE
问个小白问题啊，用这个leaf需要用什么服务端配套使用？

### ISSUE THREAD

**Issue by 52yaoer** [eycorsican/leaf#396]

**Comment by MakeMoney-Hash** [comment]
> 

就用leaf本身最好

**Comment by yeshaohuapro** [comment]
leaf可以做服务端吗？

**Comment by 52yaoer** [comment]
我也想知道leaf是否可以做服务端？

**Comment by zzuzjl** [comment]
> 我也想知道leaf是否可以做服务端？

https://github.com/eycorsican/leaf/blob/master/leaf/tests/test_tls_trojan.rs 这个是服务器的搭建配置文件

**Comment by 52yaoer** [comment]
还是没明白，我有点愚笨。。
我下载leaf-x86_64-unknown-linux-musl文件后，如何在服务端运行呢？

./leaf-x86_64-unknown-linux-musl -c server.conf 

是这样运行么？
其中的server.conf在服务端如何配置呢？
