### ISSUE TITLE
Reload doesn't seem to work.

### ISSUE THREAD

**Issue by sayhell** [eycorsican/leaf#404]
Reload doesn't seem to work.

After reload:

```
[INFO] reloading from config file: /data/user/0/com.example.vpn/configs/runtime.conf
[DEBUG] default handler [DIRECT]
[TRACE] add handler [DIRECT]
[INFO] reloaded from config file: /data/user/0/com.example.vpn/configs/runtime.conf
```

There are still logs showing some links transferred via proxy.

```
[DEBUG] tcp link 10.0.0.1:37268 <-> <ip>:<port> done, (1549, 17647) bytes transfered [PROXY]
[DEBUG] tcp link 10.0.0.1:37288 <-> <ip>:<port> done, (642, 290) bytes transfered [PROXY]
```

**Comment by sayhell** [comment]
I found out the Leaf wouldn't reset the previous link after reloading. Can the previous links be cut down?

**Comment by sayhell** [comment]
By the way, the leaf reload function returns 0 success.

**Comment by eycorsican** [comment]
Reloading config will not interrupt existing connections.


> Can the previous links be cut down?

Then it's not a reload, it's a restart, and you can do that already.

**Comment by sayhell** [comment]
Thanks, that means we should restart the VpnService because the shutdown function will close the FD. Is that correct?

**Comment by eycorsican** [comment]
Yeah, leaf takes the ownership of the tun fd and closes it on shutdown.
