### ISSUE TITLE
iOS:用一样的配置在12.4.1系统上正常代理，但是在16.3.1上面不能正常代理，你们遇见了么？

### ISSUE THREAD

**Issue by 52yaoer** [eycorsican/leaf#407]

**Comment by 52yaoer** [comment]
同样的配置，在iOS 12 、14上测试正常，但是16上测试不能正常连接。。

哪位大神可以告知下解决方法啊。非常感谢。。。

**Comment by 52yaoer** [comment]
配置如下：

[General]
loglevel = trace
dns-server = 223.5.5.5, 114.114.114.114
tun-fd = REPLACE-ME-WITH-THE-FD
routing-domain-resolve = true

[Proxy]
Direct = direct
Proxy = trojan, jiedian1.ozhong.vip, 443, password=123456
[Rule]
EXTERNAL, site:cn, Direct
EXTERNAL, mmdb:cn, Direct
FINAL, Proxy

**Comment by loveCodingStar** [comment]
1.获取tunnel的方式对不对
2.tunnel是怎么创建的

**Comment by 52yaoer** [comment]
用的是这个，





import NetworkExtension

let appGroup = "group.com.soft.qingyanjiasu"

// See https://github.com/eycorsican/leaf/blob/master/README.zh.md#conf for more conf examples.
let conf = """
[General]
loglevel = trace
dns-server = 223.5.5.5, 114.114.114.114
tun-fd = REPLACE-ME-WITH-THE-FD
routing-domain-resolve = true

[Proxy]
Direct = direct
Proxy = trojan, jiedian1.ozhong.vip, 443, password=ShadkyYye1
[Rule]
EXTERNAL, site:cn, Direct
EXTERNAL, mmdb:cn, Direct
FINAL, Proxy
"""

class PacketTunnelProvider: NEPacketTunnelProvider {
    override func startTunnel(options: [String : NSObject]?, completionHandler: @escaping (Error?) -> Void) {
        let tunnelNetworkSettings = createTunnelSettings()
        setTunnelNetworkSettings(tunnelNetworkSettings) { [weak self] error in
            let tunFd = self?.packetFlow.value(forKeyPath: "socket.fileDescriptor") as! Int32
            let confWithFd = conf.replacingOccurrences(of: "REPLACE-ME-WITH-THE-FD", with: String(tunFd))
            let url = FileManager().containerURL(forSecurityApplicationGroupIdentifier: appGroup)!.appendingPathComponent("running_config.conf")
            do {
                try confWithFd.write(to: url, atomically: false, encoding: .utf8)
            } catch {
                NSLog("fialed to write config file \(error)")
            }
            // The CA is used by OpenSSl.
            // You may download a CA from https://curl.se/docs/caextract.html
            var certPath = Bundle.main.executableURL?.deletingLastPathComponent()
            setenv("SSL_CERT_DIR", certPath?.path, 1)
            certPath?.appendPathComponent("cacert.pem")
            setenv("SSL_CERT_FILE", certPath?.path, 1)
            DispatchQueue.global(qos: .userInteractive).async {
                signal(SIGPIPE, SIG_IGN)
                leaf_run(999,url.path)
            }
            completionHandler(nil)
        }
    }
    
    override func stopTunnel(with reason: NEProviderStopReason, completionHandler: @escaping () -> Void) {
        leaf_shutdown(999)
        completionHandler()
    }
    
    override func handleAppMessage(_ messageData: Data, completionHandler: ((Data?) -> Void)?) {
        // Add code here to handle the message.
        if let handler = completionHandler {
            handler(messageData)
        }
    }
    
    override func sleep(completionHandler: @escaping () -> Void) {
        // Add code here to get ready to sleep.
        completionHandler()
    }
    
    override func wake() {
        // Add code here to wake up.
    }
    
    func createTunnelSettings() -> NEPacketTunnelNetworkSettings  {
        let newSettings = NEPacketTunnelNetworkSettings(tunnelRemoteAddress: "240.0.0.10")
        newSettings.ipv4Settings = NEIPv4Settings(addresses: ["240.0.0.1"], subnetMasks: ["255.255.255.0"])
        newSettings.ipv4Settings?.includedRoutes = [NEIPv4Route.`default`()]
        newSettings.proxySettings = nil
        newSettings.dnsSettings = NEDNSSettings(servers: ["223.5.5.5", "8.8.8.8"])
        newSettings.mtu = 1500
        return newSettings
    }
}

**Comment by loveCodingStar** [comment]
你去查一下tunfd的获取方式吧，iOS15之后就有变化了

**Comment by 52yaoer** [comment]
难道iOS 16 系统 获取 tunnel 方式变化了？

**Comment by loveCodingStar** [comment]
google一下吧

**Comment by 52yaoer** [comment]
if #available(iOS 15, *) {
var buf = [CChar](repeating: 0, count: Int(IFNAMSIZ))
let utunPrefix = "utun".utf8CString.dropLast()
return (0...1024).first { (_ fd: Int32) -> Bool in
var len = socklen_t(buf.count)
return getsockopt(fd, 2, 2, &buf, &len) == 0 && buf.starts(with: utunPrefix)
}
} else {
return self.packetFlow.value(forKeyPath: "socket.fileDescriptor") as? Int32
}

**Comment by 52yaoer** [comment]
找到原因了，。。谢谢，，，终于可以正常使用了

**Comment by loveCodingStar** [comment]
有问题线google就对了，哈哈哈
