### ISSUE TITLE
请教一下到底 是否支持vmess

### ISSUE THREAD

**Issue by laowant** [eycorsican/leaf#410]
我现在 SS和 trojan 都可以正常访问， 但是Vmess就始终没有办法连通使用。 我看历史问题里有些人说 vmess没支持过。这个是我代码的问题。还是确定不支持vmess？

**Comment by loveCodingStar** [comment]
以前支持，现在不支持了，代码没写vmess的aead

**Comment by laowant** [comment]
> 

大哥 你会改Vmess的 AEAD吗

**Comment by loveCodingStar** [comment]
你可以留下你的联系方式

**Comment by cnryb** [comment]
v2fly-core:v4.27.5 之前的版本支持

**Comment by Web3123** [comment]
https://github.com/Web3123/v2ray 这是项目地址
