### ISSUE TITLE
谁指教下windows11如何使用啊？

### ISSUE THREAD

**Issue by 52yaoer** [eycorsican/leaf#427]
我是这样做的，
1.右键把leaf-x86_64-pc-windows-gnu.exe文件设置为管理员运行权限。
2.leaf-x86_64-pc-windows-gnu.exe -c config1.conf

cmd弹出内容只有这样点内容。

[2m2023-10-12T15:15:09.238525Z[0m [34mDEBUG[0m [2mleaf::app::outbound::manager[0m[2m:[0m default handler [Proxy]
[2m2023-10-12T15:15:09.238751Z[0m [35mTRACE[0m [2mleaf::app::outbound::manager[0m[2m:[0m add handler [Proxy]
[2m2023-10-12T15:15:09.238767Z[0m [35mTRACE[0m [2mleaf::app::outbound::manager[0m[2m:[0m add handler [Direct]
[2m2023-10-12T15:15:09.238943Z[0m [35mTRACE[0m [2mleaf[0m[2m:[0m added runtime 0

**Comment by 52yaoer** [comment]
我的配置文件如下


[General]
 loglevel = trace
 dns-server = 223.5.5.5, 114.114.114.114
 tun = auto
 routing-domain-resolve = true
[Proxy] 
Direct = direct
Proxy = ........详细配置信息...........
[Rule] 
FINAL, Proxy

**Comment by 52yaoer** [comment]
以上配置在macos 可以正常运行。

sudo ./leaf-0.9.3 -c config1.conf

**Comment by laowant** [comment]
兄弟你搞定了吗？ 可以教教我 windows怎么搞吗

**Comment by laowant** [comment]
兄弟  我推荐你用Xray 如果是windows。 leaf最大的优点只在于ios。 目前我没发现其他内核能稳定运行ios。 唯有leaf

**Comment by 52yaoer** [comment]
目前研究出用系统代理方式，在win系统中使用，没有研究出如何用tun模式。
