### ISSUE TITLE
ios 的geosite.dat放在哪里呢？

### ISSUE THREAD

**Issue by garymaxallen** [eycorsican/leaf#431]
如题

**Comment by loveCodingStar** [comment]
你的pakcettunnel放哪里，它就放哪里

**Comment by garymaxallen** [comment]
我是在app store上面下载的。你的意思是要自己编译吗？

**Comment by loveCodingStar** [comment]
什么叫下载的，不懂，你不是在开发vpn应用吗？还是在砸壳

**Comment by garymaxallen** [comment]
不是开发啊，我直接在苹果商店下载的。

**Comment by garymaxallen** [comment]
在苹果商店下载的leaf vpn

**Comment by loveCodingStar** [comment]
那它不是内置了吗

**Comment by garymaxallen** [comment]
我加了这个规则，好像没生效。
EXTERNAL, site:geosite.dat:cn, Direct

**Comment by garymaxallen** [comment]
这是全部的配置文件，windows上面用maple是没问题的。


[General]
loglevel = error
tun = auto
# dns use system dns, do not use 8.8.8.8
dns-server = 223.5.5.5

[Proxy]
Direct = direct
Reject = reject
server104 = vmess, xxxxxxx
server237 = vmess, xxxxxx

[Rule]
IP-CIDR, 192.168.0.0/16, Direct
IP-CIDR, 10.11.0.0/16, server237
EXTERNAL, site:geosite.dat:cn, Direct
FINAL, server104

**Comment by loveCodingStar** [comment]
leaf不支持最新的vmess

**Comment by garymaxallen** [comment]
不是vmess的问题吧，我用的一个旧版本是可以的。现在的问题是geosite规则不生效。vpn是能用的，就是全部走的代理。
