### ISSUE TITLE
iOS VMess, VMessWSS - SSL error

### ISSUE THREAD

**Issue by corgisupercode** [eycorsican/leaf#448]
I success connected  with ss and trojan, but can not connect with VMess and VMessWSS.
"cacert.pem" also added to project 
tun-fd also replaced

`var certPath = Bundle.main.executableURL?.deletingLastPathComponent()
            setenv("SSL_CERT_DIR", certPath?.path, 1)
            // NSLog("certPath = \(certPath!.path)")
            certPath?.appendPathComponent("cacert.pem")
            NSLog("certPath = \(certPath?.path)")
            setenv("SSL_CERT_FILE", certPath?.path, 1)`

My conf:
---------
[General]
loglevel = debug
dns-server = 223.5.5.5, 8.8.8.8
tun-fd = REPLACE-ME-WITH-THE-FD
routing-domain-resolve = true

interface = 127.0.0.1
port = 1087

socks-interface = 127.0.0.1
socks-port = 1086

[Proxy]
#SS = ss, MY_SERVER_IP, 1080, encrypt-method=chacha20-ietf-poly1305, password=mypass
#TrojanWS = trojan, MY_SERVER_IP, 2083, password=mypass,tls-insecure=true, tls=true, sni=825bcb48ee1c3929.metric.gstatic.com, ws=true, ws-path=/
#VMess = vmess, MY_SERVER_IP, 8081, username=cce1dcd4-ad51-471e-bf61-07b7e156d9b2
VMessWSS = vmess, MY_SERVER_IP, 8080, username=2002b73f-60dd-402a-8e11-b5fdcad37ca2, tls=true, ws=true, ws-path=/
--------

Error in logs
`Jan 27 20:21:38 PacketTunnel[45416] <Notice>: 2024-01-27T19:21:38.732979Z DEBUG leaf::app::dispatcher: dispatch tcp 240.0.0.1:59688 -> configuration.apple.com:443 to [VMessWSS] failed: connect ssl stream failed: error:0A0000C6:SSL routines:tls_get_more_records:packet length too long:ssl/record/methods/tls_common.c:649:, error:0A000139:SSL routines::record layer failure:ssl/record/rec_layer_s3.c:646:
Jan 27 20:21:38 PacketTunnel[45416] <Notice>: 2024-01-27T19:21:38.733019Z  INFO leaf::app::dispatcher: [240.0.0.1] [tcp] [tun] [VMessWSS] [failed] [configuration.apple.com:443]`

Does it work for anyone? What could be the reason? I've been looking for two days now.

**Comment by eycorsican** [comment]
1. try the same config on desktop
2. check your server config

**Comment by eycorsican** [comment]
i guess it's vmessaead on your server, which is not supported by leaf

**Comment by loveCodingStar** [comment]
有telegram？可以一起讨论下

**Comment by Cyberbolt** [comment]
@corgisupercode  Hi, I also encountered the same error as you, but only on iOS. macOS can connect to Vmess normally using the same configuration file. However, when connecting to iOS, the same error as yours appears. What is the reason?

**Comment by MoneyKey11** [comment]
> Hi, I also encountered the same error as you, but only on iOS. macOS can connect to Vmess normally using the same configuration file. However, when connecting to iOS, the same error as yours appears. What is the reason?

your telegram, we can discuss

**Comment by Web3123** [comment]
> @loveCodingStar my or repository owner?

your
