### ISSUE TITLE
I built v2ray ios demo

### ISSUE THREAD

**Issue by newfuture33** [eycorsican/leaf#452]
If you want to develop v2ray app, please contact to me。

Skype: live:.cid.85b9ef80726be21e
QQ：2890152926
Telegram: @GameKing713
Email: [newfuture33@126.com](mailto:newfuture33@126.com)

**Comment by Web3123** [comment]
very good

**Comment by Web3123** [comment]
https://github.com/Web3123/v2ray 这是项目地址
