### ISSUE TITLE
iOS 上运行 shadowsocks 启动内存超过 50MB

### ISSUE THREAD

**Issue by Cyberbolt** [eycorsican/leaf#457]
超过 50MB 的瞬间 VPN 会崩溃，请问有解决方案吗

**Comment by MoneyKey11** [comment]
你的tg多少 可以一起讨论下

**Comment by Cyberbolt** [comment]
> 你的tg多少 可以一起讨论下

@Cyberbolt_git

**Comment by Cyberbolt** [comment]
iOS 上 Tun 模式和 SS 同时开启的时候，启动时最大内存会超过 50 MB，导致 VPN 连接断开。如果单独打开 Tun 模式或 SS，都不会出现该问题。这种情况导致 iOS 上无法运行 SS，应该是 SS Outbounds 算法实现有问题，Golang 版本的 SS 都可以正常启动

**Comment by Cyberbolt** [comment]
我测试了 leaf 的官方 iOS 客户端，还是一样的问题，只要 outbounds 是 ss 就断开

**Comment by Cyberbolt** [comment]
Bug
