### ISSUE TITLE
加一个mipsle版本啊

### ISSUE THREAD

**Issue by LGTMXD** [eycorsican/leaf#6]
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.15/build.rs:378:10

这是什么错误 我昨天用actions编译的时候也出现这问题，然后就没搞了

briansmith/ring#562

**Comment by josh-chan** [comment]
顺便加一个 arm 版本

**Comment by eycorsican** [comment]
`ring`, the crypto library used by leaf, [does not support mips](https://github.com/briansmith/ring#online-automated-testing), we need another crypto library for this.

**Comment by eycorsican** [comment]
mips/mipsel supported in v0.2.3
