### ISSUE TITLE
I want to use this library to make an app

### ISSUE THREAD

**Issue by cyandnow** [eycorsican/leaf#7]
I want to use this library to make an app, but at present, the content of this document only talks about configuration. What other additional operations do I need to do?

Thank you.

**Comment by eycorsican** [comment]
It depends on what platform your app is targeting. You almost just need a valid config file and knowing how to link a static library on you target platform.

**Comment by cyandnow** [comment]
> It depends on what platform your app is targeting. You almost just need a valid config file and knowing how to link a static library on you target platform.

Thank you for your reply. I want to make an iOS app. is continue to use the packet tunnel,
In addition, can your testlight version of APP code be open source?

**Comment by eycorsican** [comment]
An iOS demo is published: https://github.com/eycorsican/ileaf

**Comment by cyandnow** [comment]
> An iOS demo is published: https://github.com/eycorsican/ileaf

Thank you very much!!!
