### ISSUE TITLE
tun模式ssh连接

### ISSUE THREAD

**Issue by Esinchung** [eycorsican/leaf#8]
在路由器上运行leaf的tun模式后，能正常分流代理，但是有个问题本机至路由器间ssh无法连接，改配置只能通过路由器主机接显示器、键盘，很不方便，有后什么办法绕过去么

**Comment by eycorsican** [comment]
`ping` your router, see: https://github.com/mellow-io/mellow/blob/master/README.1.md#%E5%8F%AF%E4%BB%A5%E5%9C%A8-linux-%E4%B8%8A%E4%BB%A5%E5%91%BD%E4%BB%A4%E8%A1%8C%E6%96%B9%E5%BC%8F%E8%BF%90%E8%A1%8C%E5%90%97

**Comment by Esinchung** [comment]
试了下还是会断，先这样吧
