### ISSUE TITLE
Release leaf without zip/gzip

### ISSUE THREAD

**Issue by sayomelu** [eycorsican/leaf#88]
since leaf release is very small, and only has one file, which doesn't contain the `geo.mmdb` and `site.dat` file. it is easier to use without zip/gzip format.

when i want to update leaf, i have to use.
```
curl -LO https://github.com/eycorsican/leaf/releases/latest/download/leaf-x86_64-apple-darwin.gz
gzip -df leaf-x86_64-apple-darwin.gz
chmod +x ./leaf-x86_64-apple-darwin
```

**Comment by kidonng** [comment]
You don't have to update manually if Homebrew/homebrew-core#72070 is accepted.

**Comment by kidonng** [comment]
You can now install leaf with `brew install leaf-proxy`.
