### ISSUE TITLE
[iOS] Build for x86_64 (running in simulator)

### ISSUE THREAD

**Issue by pamartn** [eycorsican/leaf#89]
Hi,

Currently the application cannot be built for x86_64 simulator because the _libleaf.a_ supports only arm64.
```
$ lipo -info libleaf.a                         
Architectures in the fat file: libleaf.a are: arm64
```

Any hints on how to compile _libleaf.a_ for arm64 & x86_64 ?
I know it is located at https://github.com/eycorsican/leaf/tree/master/leaf-mobile but I don't know how to update build files.

Thanks a lot

**Comment by eycorsican** [comment]
```sh
rustup target add aarch64-apple-ios 
cargo lipo -p leaf-mobile --release --targets aarch64-apple-ios aarch64-apple-ios --manifest-path leaf-mobile/Cargo.toml 
```

**Comment by pamartn** [comment]
That is perfect ! Thanks a lot for your quick answer and for open sourcing the lib 👍

**Comment by fuqiangleon** [comment]
> ```shell
> rustup target add x86_64-apple-ios
> cargo lipo -p leaf-mobile --release --targets x86_64-apple-ios aarch64-apple-ios --manifest-path leaf-mobile/Cargo.toml 
> ```



> ```shell
> rustup target add x86_64-apple-ios
> cargo lipo -p leaf-mobile --release --targets x86_64-apple-ios aarch64-apple-ios --manifest-path leaf-mobile/Cargo.toml 
> ```

@eycorsican  Seems the repo struct has been changed?  how to fix it ?

**Comment by fuqiangleon** [comment]
@pamartn hey, bro,  did you build the lib successfully?
