### ISSUE TITLE
h2+vmess error

### ISSUE THREAD

**Issue by KeyonYe** [eycorsican/leaf#90]
<img width="1178" alt="截屏2021-03-13 下午6 54 56" src="https://user-images.githubusercontent.com/46473120/111027849-ccd77880-842d-11eb-9f4d-62b08030aced.png">

**Comment by eycorsican** [comment]
Please describe the issue in detail.

**Comment by KeyonYe** [comment]
> Please describe the issue in detail.

我设置了tls+h2+vmess。加密算法aes-128-gcm。在小火箭可以用。但是leaf的不行
