### ISSUE TITLE
leaf-mobile 0.2.13, more memory usage

### ISSUE THREAD

**Issue by never-afk** [eycorsican/leaf#98]
it's seem that  recent version(0.2.13)  will consume more memory .
for example,trojan with default option `ENDPOINT_TCP_CONCURRENCY = 45`   crash.
that never happen on version 0.2.7

btw,vmess/ss without tls  is ok, but the memory will achieve **13-14M**,it's a little bit danger ?
(i changed `ENDPOINT_TCP_CONCURRENCY = 128`)

```
[General]
loglevel = trace
dns-server = 223.5.5.5, 114.114.114.114
tun-fd = REPLACE-ME-WITH-THE-FD
[Proxy]
Direct = direct
VMess = vmess, x.x.x.x, 10086, username=23ad6b10-8d1a-40f7-8ad0-e3e35cd38297
t = trojan, x.x.x.x, 443, password=123456, sni=xx.xxx.com
[Rule]
FINAL, t
```

**Comment by eycorsican** [comment]
Consider to remove unnecessary features: https://github.com/eycorsican/leaf#customizing-build

**Comment by never-afk** [comment]
after a lot of  time testing still same result .

```
leaf-mobile/Cargo.toml

[features]
default = [
    "leaf/all-configs",
    "leaf/all-endpoints",
    "leaf/rustls-tls"
]


leaf/Cargo.toml

all-endpoints = [
    # inbounds
    "inbound-tun",
    # outbounds
    "outbound-direct",
    "outbound-drop",
    "outbound-trojan",
    "outbound-tls",
    "outbound-chain"
]

```

that makes smaller binary size ,but no change for runtime memory.

i believe that features config may be minimum necessary features for trojan on ios.

**Comment by Xx0101** [comment]
> after a lot of time testing still same result .
> 
> ```
> leaf-mobile/Cargo.toml
> 
> [features]
> default = [
>     "leaf/all-configs",
>     "leaf/all-endpoints",
>     "leaf/rustls-tls"
> ]
> 
> 
> leaf/Cargo.toml
> 
> all-endpoints = [
>     # inbounds
>     "inbound-tun",
>     # outbounds
>     "outbound-direct",
>     "outbound-drop",
>     "outbound-trojan",
>     "outbound-tls",
>     "outbound-chain"
> ]
> ```
> 
> that makes smaller binary size ,but no change for runtime memory.
> 
> i believe that features config may be minimum necessary features for trojan on ios.

Did you solve it？

**Comment by never-afk** [comment]
解决不了，本人rust水平有限。

**Comment by Xx0101** [comment]
> 解决不了，本人rust水平有限。

trojan确实很容易崩溃,我现在都不知道是memory崩溃还是哪里执行问题,大概率memory

**Comment by never-afk** [comment]
> > 解决不了，本人rust水平有限。
> 
> trojan确实很容易崩溃,我现在都不知道是memory崩溃还是哪里执行问题,大概率memory

核心原因不在Trojan上面,而是在于TLS握手产生的额外开销.你可以尝试Vmess+tls,一样会崩溃.
作者已经把open-tls换成rust-tls了,但是还是不可解决.

@eycorsican 曾经是一名资深go,因为这个15M问题,所以转向rust来解决内存开销问题

我看过leaf代码,理论上没有什么优化空间了.
那么是不是类Tls的代理软件都不能再IOS上流畅稳定运行呢?
答案是可以的,shadowrocket就是ios平台的领头羊,因为没开源,所以也不可得知怎么处理这一问题.

**Comment by eycorsican** [comment]
Regarding openssl, I believe there's still a large option space to explore.

https://docs.rs/openssl/0.10.33/openssl/ssl/struct.SslOptions.html
https://docs.rs/openssl/0.10.33/openssl/ssl/struct.SslMode.html

Have you tried all these options?
